/**
 * Dicionário estático de correção ortográfica para 13 idiomas.
 * Lookup O(1) — zero rede, zero bloqueio.
 * Cada entrada mapeia palavra errada → palavra correta.
 */

// ═══════════════════════════════════════════════════════════
// PORTUGUÊS (pt) — ~2.000 entradas
// ═══════════════════════════════════════════════════════════
const pt: Record<string, string> = {
  // ── Artigos, preposições, contrações ──
  "ah": "a", "ao": "ao", "aos": "aos", "aqui": "aqui", "aquele": "aquele",
  "aquela": "aquela", "aqueles": "aqueles", "aquelas": "aquelas", "aquilo": "aquilo",
  "ate": "até", "as": "as", "ateh": "até", "ahh": "ah",

  // ── Erros comuns de acentuação ──
  "voce": "você", "vocez": "você", "voces": "vocês", "ele": "ele", "ela": "ela",
  "tambem": "também", "tambe": "também", "tambem": "também",
  "nao": "não", "não": "não", "naum": "não", "num": "não",
  "sim": "sim", "nao": "não",
  "porem": "porém", "porquem": "por quem",
  "ninguem": "ninguém", "ninguen": "ninguém",
  "alguem": "alguém", "alguen": "alguém",
  "alem": "além", "alemm": "além",
  "ate": "até", "ateh": "até",
  "ja": "já", "jah": "já",
  "so": "só", "soh": "só",
  "pos": "pós", "pos": "pós",
  "pre": "pré", "preh": "pré",
  "pro": "pro", "util": "útil", "util": "útil", "utill": "útil",
  "facil": "fácil", "facill": "fácil", "faci": "fácil",
  "dificil": "difícil", "dificill": "difícil",
  "possivel": "possível", "possivell": "possível",
  "impossivel": "impossível",
  "util": "útil", "inutil": "inútil", "inutill": "inútil",
  "necessario": "necessário", "necessario": "necessário",
  "obrigado": "obrigado", "obrigada": "obrigada",
  "porque": "porque", "porke": "porque", "porqe": "porque",
  "porquê": "porquê", "porques": "porquês",

  // ── Verbos comuns ──
  "eh": "é", "e": "é", "esta": "está", "estah": "está",
  "estao": "estão", "estao": "estão", "estao": "estão",
  "tinha": "tinha", "tinhas": "tinhas", "tinha": "tinha",
  "faz": "faz", "faz": "faz", "fazer": "fazer",
  "tem": "tem", "teem": "têm", "temm": "têm",
  "vem": "vem", "veem": "vêm", "vemm": "vêm",
  "pode": "pode", "podem": "podem",
  "quer": "quer", "querem": "querem",
  "sabe": "sabe", "sabem": "sabem",
  "vai": "vai", "vão": "vão", "vaum": "vão",
  "sao": "são", "saum": "são",
  "foi": "foi", "foram": "foram",
  "era": "era", "eram": "eram",
  "sera": "será", "serao": "serão", "seram": "serão",
  "teria": "teria", "teriam": "teriam",
  "fará": "fará", "farao": "farão",
  "havera": "haverá", "haveria": "haveria",
  "consegue": "consegue", "conseguem": "conseguem",
  "precisa": "precisa", "precisam": "precisam",
  "gosta": "gosta", "gostam": "gostam",
  "preciso": "preciso", "precisamos": "precisamos",
  "quero": "quero", "queremos": "queremos",
  "posso": "posso", "podemos": "podemos",
  "devo": "devo", "devemos": "devemos",
  "falo": "falo", "falamos": "falamos",
  "entendo": "entendo", "entendem": "entendem",
  "acho": "acho", "acham": "acham",
  "acho": "acho", "achou": "achou",
  "comeco": "começo", "começa": "começa", "comeca": "começa",
  "comecar": "começar", "começar": "começar",
  "comecou": "começou", "comecou": "começou",
  "continua": "continua", "continua": "continua",
  "continuar": "continuar", "continuar": "continuar",
  "funciona": "funciona", "funcionar": "funcionar",
  "tentar": "tentar", "tentou": "tentou",
  "conseguir": "conseguir", "conseguiu": "conseguiu",
  "dar": "dar", "deu": "deu", "deram": "deram",
  "ver": "ver", "viu": "viu", "viram": "viram",
  "ir": "ir", "fui": "fui", "fomos": "fomos",
  "vir": "vir", "veio": "veio", "vieram": "vieram",
  "ter": "ter", "tive": "tive", "tivemos": "tivemos",
  "haver": "haver", "houve": "houve",
  "saber": "saber", "soube": "soube",
  "querer": "querer", "quis": "quis",
  "fazer": "fazer", "fez": "fez", "fiz": "fiz",
  "dizer": "dizer", "disse": "disse", "disseram": "disseram",
  "poder": "poder", "pude": "pude",
  "estar": "estar", "estive": "estive",
  "ser": "ser", "fui": "fui",
  "ter": "ter", "havia": "havia",
  "andar": "andar", "andou": "andou",
  "pensar": "pensar", "pensou": "pensou",
  "falar": "falar", "falou": "falou",
  "comer": "comer", "comeu": "comeu",
  "beber": "beber", "bebeu": "bebeu",
  "dormir": "dormir", "dormiu": "dormiu",
  "acordar": "acordar", "acordou": "acordou",
  "abrir": "abrir", "abriu": "abriu",
  "fechar": "fechar", "fechou": "fechou",
  "escrever": "escrever", "escreveu": "escreveu",
  "ler": "ler", "leu": "leu",
  "ouvir": "ouvir", "ouviu": "ouviu",
  "ver": "ver", "viu": "viu",
  "olhar": "olhar", "olhou": "olhou",
  "procurar": "procurar", "procurou": "procurou",
  "encontrar": "encontrar", "encontrou": "encontrou",
  "perder": "perder", "perdeu": "perdeu",
  "ganhar": "ganhar", "ganhou": "ganhou",
  "vencer": "vencer", "venceu": "venceu",
  "perder": "perder",
  "jogar": "jogar", "jogou": "jogou",
  "usar": "usar", "usou": "usou",
  "precisar": "precisar", "precisou": "precisou",
  "tentar": "tentar", "tentou": "tentou",
  "ajudar": "ajudar", "ajudou": "ajudou",
  "deixar": "deixar", "deixou": "deixou",
  "levar": "levar", "levou": "levou",
  "trazer": "trazer", "trouxe": "trouxe",
  "pegar": "pegar", "pegou": "pegou",
  "colocar": "colocar", "colocou": "colocou",
  "tirar": "tirar", "tirou": "tirou",
  "dar": "dar", "deu": "deu",
  "comprar": "comprar", "comprou": "comprou",
  "vender": "vender", "vendeu": "vendeu",
  "trocar": "trocar", "trocou": "trocou",
  "mudar": "mudar", "mudou": "mudou",
  "voltar": "voltar", "voltou": "voltou",
  "entrar": "entrar", "entrou": "entrou",
  "sair": "sair", "saiu": "saiu",
  "subir": "subir", "subiu": "subiu",
  "descer": "descer", "desceu": "desceu",
  "cair": "cair", "caiu": "caiu",
  "morrer": "morrer", "morreu": "morreu",
  "viver": "viver", "viveu": "viveu",
  "nascer": "nascer", "nasceu": "nasceu",
  "crescer": "crescer", "cresceu": "cresceu",
  "aprender": "aprender", "aprendeu": "aprendeu",
  "ensinar": "ensinar", "ensinou": "ensinou",
  "estudar": "estudar", "estudou": "estudou",
  "trabalhar": "trabalhar", "trabalhou": "trabalhou",
  "descansar": "descansar", "descansou": "descansou",
  "esperar": "esperar", "esperou": "esperou",
  "espera": "espera", "esperam": "esperam",
  "acreditar": "acreditar", "acreditou": "acreditou",
  "lembrar": "lembrar", "lembrou": "lembrou",
  "esquecer": "esquecer", "esqueceu": "esqueceu",
  "gostar": "gostar", "gostou": "gostou",
  "amar": "amar", "amou": "amou",
  "odar": "odiar", "odiar": "odiar", "odiou": "odiou",
  "brincar": "brincar", "brincou": "brincou",
  "correr": "correr", "correu": "correu",
  "nadar": "nadar", "nadou": "nadou",
  "pular": "pular", "pulou": "pulou",
  "caminhar": "caminhar", "caminhou": "caminhou",
  "viajar": "viajar", "viajou": "viajou",
  "chegar": "chegar", "chegou": "chegou",
  "partir": "partir", "partiu": "partiu",
  "ficar": "ficar", "ficou": "ficou",
  "parecer": "parecer", "pareceu": "pareceu",
  "ficar": "ficar",
  "acontecer": "acontecer", "aconteceu": "aconteceu",
  "parecer": "parecer",
  "existir": "existir", "existe": "existe", "existem": "existem",
  "parece": "parece", "parecem": "parecem",

  // ── Substantivos comuns ──
  "dia": "dia", "noite": "noite", "manha": "manhã", "manhã": "manhã",
  "tarde": "tarde", "madrugada": "madrugada",
  "semana": "semana", "mes": "mês", "ano": "ano",
  "meses": "meses", "anos": "anos", "dias": "dias", "noites": "noites",
  "hoje": "hoje", "ontem": "ontem", "amanha": "amanhã", "amanhã": "amanhã",
  "sempre": "sempre", "nunca": "nunca",
  "agora": "agora", "logo": "logo", "depois": "depois",
  "antes": "antes", "ainda": "ainda",
  "muito": "muito", "pouco": "pouco",
  "mais": "mais", "menos": "menos",
  "tudo": "tudo", "nada": "nada",
  "cada": "cada", "todo": "todo", "toda": "toda", "todos": "todos", "todas": "todas",
  "outro": "outro", "outra": "outra", "outros": "outros", "outras": "outras",
  "mesmo": "mesmo", "mesma": "mesma", "mesmos": "mesmos",
  "tanto": "tanto", "tanta": "tanta",
  "quanto": "quanto", "quanta": "quanta", "quantos": "quantos",
  "bom": "bom", "boa": "boa", "bons": "bons", "boas": "boas",
  "mau": "mau", "má": "má", "maus": "maus", "más": "más",
  "grande": "grande", "grandes": "grandes",
  "pequeno": "pequeno", "pequena": "pequena", "pequenos": "pequenos",
  "bonito": "bonito", "bonita": "bonita", "bonitos": "bonitos",
  "feio": "feio", "feia": "feia",
  "alto": "alto", "alta": "alta", "altos": "altos",
  "baixo": "baixo", "baixa": "baixa",
  "longe": "longe", "perto": "perto",
  "aqui": "aqui", "ali": "ali", "lá": "lá", "cá": "cá",
  "este": "este", "esta": "esta", "estes": "estes", "estas": "estas",
  "esse": "esse", "essa": "essa", "esses": "esses", "essas": "essas",
  "isto": "isto", "isso": "isso", "aquilo": "aquilo",

  // ── Substantivos do jogo/comum ──
  "jogo": "jogo", "jogos": "jogos",
  "item": "item", "itens": "itens",
  "player": "player", "players": "players",
  "sobrevivente": "sobrevivente", "sobreviventes": "sobreviventes",
  "zumbi": "zumbi", "zumbis": "zumbis",
  "arma": "arma", "armas": "armas",
  "municao": "munição", "munição": "munição",
  "comida": "comida", "comidas": "comidas",
  "agua": "água", "água": "água",
  "remedio": "remédio", "remédio": "remédio",
  "bandagem": "bandagem", "bandagens": "bandagens",
  "mochila": "mochila", "mochilas": "mochilas",
  "base": "base", "bases": "bases",
  "casa": "casa", "casas": "casas",
  "cidade": "cidade", "cidades": "cidades",
  "mapa": "mapa", "mapas": "mapas",
  "lugar": "lugar", "lugares": "lugares",
  "porta": "porta", "portas": "portas",
  "chave": "chave", "chaves": "chaves",
  "ferramenta": "ferramenta", "ferramentas": "ferramentas",
  "madeira": "madeira",
  "pedra": "pedra", "pedras": "pedras",
  "metal": "metal", "metais": "metais",
  "roupa": "roupa", "roupas": "roupas",
  "dinheiro": "dinheiro",
  "troca": "troca", "trocas": "trocas",
  "venda": "venda", "vendas": "vendas",
  "compra": "compra", "compras": "compras",
  "preco": "preço", "preço": "preço", "preços": "preços",
  "valor": "valor", "valores": "valores",
  "negocio": "negócio", "negócio": "negócio",
  "acordo": "acordo", "acordos": "acordos",
  "clan": "clã", "clãs": "clãs", "clas": "clãs",
  "guilda": "guilda", "guildas": "guildas",
  "grupo": "grupo", "grupos": "grupos",
  "equipe": "equipe", "equipes": "equipes",
  "amigo": "amigo", "amigos": "amigos",
  "amiga": "amiga", "amigas": "amigas",
  "inimigo": "inimigo", "inimigos": "inimigos",
  "admin": "admin", "adm": "admin",
  "moderador": "moderador", "moderadores": "moderadores",
  "regra": "regra", "regras": "regras",
  "chat": "chat", "mensagem": "mensagem", "mensagens": "mensagens",
  "canal": "canal", "canais": "canais",
  "sala": "sala", "salas": "salas",
  "servidor": "servidor", "servidores": "servidores",
  "site": "site", "sites": "sites",
  "pagina": "página", "página": "página", "páginas": "páginas",
  "link": "link", "links": "links",
  "video": "vídeo", "vídeo": "vídeo", "vídeos": "vídeos",
  "foto": "foto", "fotos": "fotos",
  "imagem": "imagem", "imagens": "imagens",

  // ── Erros de digitação comuns (teclado) ──
  "qeu": "que", "qe": "que", "quw": "que",
  "qulo": "quilo", "quilo": "quilo",
  "tao": "tão", "taum": "tão",
  "cem": "cem", "cem": "cem",
  "vo": "vou", "vi": "vi",
  "vc": "você", "vcs": "vocês",
  "tb": "também", "tbm": "também", "tmb": "também", "tamb": "também",
  "pq": "porque", "pk": "porque", "porq": "porque",
  "blz": "beleza", "bhz": "beleza",
  "flw": "falou", "valeu": "valeu",
  "kkk": "kkk", "kk": "kk",
  "noobs": "noobs", "noob": "noob",
  "nub": "noob", "nubs": "noobs",
  "haha": "haha", "kkk": "kkk",
  "ehh": "é", "eh": "é",
  "ahh": "ah", "ah": "ah",
  "ihh": "ih", "ih": "ih",
  "uhh": "uh", "uh": "uh",
  "oxe": "oxê", "oxi": "oxi",
  "eita": "eita", "eita": "eita",
  "nossa": "nossa", "caramba": "caramba",
  "droga": "droga", "merda": "merda",
  "pqp": "puta que pariu",
  "krl": "caralho",
  "ctz": "certeza", "certeza": "certeza",
  "dps": "depois",
  "obs": "obs", "obs": "observação",
  "aki": "aqui", "aqui": "aqui",
  "bli": "blz", "blz": "beleza",
  "mt": "muito", "mto": "muito",
  "td": "tudo", "tdo": "tudo",
  "ngm": "ninguém", "nngm": "ninguém",
  "algm": "alguém",
  "msm": "mesmo",
  " Jah  ": " já ",
  "so": "só", "soh": "só",
  "nao": "não", "naum": "não", "num": "não",
  "vc": "você", "vcs": "vocês",
  "eh": "é", "vcê": "você",

  // ── Palavras frequentes mal escritas ──
  "lingua": "língua", "língua": "língua", "linguas": "línguas",
  "experiencia": "experiência", "experiência": "experiência",
  "informacao": "informação", "informação": "informação", "informacoes": "informações",
  "situacao": "situação", "situação": "situação",
  "posicao": "posição", "posição": "posição",
  "direcao": "direção", "direção": "direção",
  "regiao": "região", "região": "região",
  "estacao": "estação", "estação": "estação",
  "estragao": "estação",
  "nação": "nação", "nacao": "nação",
  "correcao": "correção", "correção": "correção",
  "conexao": "conexão", "conexão": "conexão",
  "protecao": "proteção", "proteção": "proteção",
  "instrucao": "instrução", "instrução": "instrução",
  "edicao": "edição", "edição": "edição",
  "versao": "versão", "versão": "versão",
  "razao": "razão", "razão": "razão",
  "estacao": "estação",
  "preparacao": "preparação", "preparação": "preparação",
  "comunicacao": "comunicação", "comunicação": "comunicação",
  "evolucao": "evolução", "evolução": "evolução",
  "avaliacao": "avaliação", "avaliação": "avaliação",
  "organizacao": "organização", "organização": "organização",
  "populacao": "população", "população": "população",
  "fabricacao": "fabricação", "fabricação": "fabricação",
  "producao": "produção", "produção": "produção",
  "criacao": "criação", "criação": "criação",
  "danificacao": "dano",
  "verificacao": "verificação", "verificação": "verificação",
  "confirmacao": "confirmação", "confirmação": "confirmação",
  "reparacao": "reparação", "reparação": "reparação",
  "operacao": "operação", "operação": "operação",
  "acionamento": "acionamento",
  "funcionamento": "funcionamento",
  "conhecimento": "conhecimento",
  "entendimento": "entendimento",
  "entregador": "entregador",
  "entregadores": "entregadores",

  // ── Mais erros comuns de português ──
  "interessante": "interessante",
  "importante": "importante",
  "diferente": "diferente",
  "verdade": "verdade", "verdades": "verdades",
  "mentira": "mentira", "mentiras": "mentiras",
  "problema": "problema", "problemas": "problemas",
  "solucao": "solução", "solução": "solução",
  "pergunta": "pergunta", "perguntas": "perguntas",
  "resposta": "resposta", "respostas": "respostas",
  "ajuda": "ajuda", "ajudas": "ajudas",
  "dica": "dica", "dicas": "dicas",
  "guia": "guia", "guias": "guias",
  "tutorial": "tutorial", "tutoriais": "tutoriais",
  "estrategia": "estratégia", "estratégia": "estratégia",
  "dificuldade": "dificuldade",
  "nivel": "nível", "nível": "nível", "níveis": "níveis",
  "fase": "fase", "fases": "fases",
  "missao": "missão", "missão": "missão", "missões": "missões",
  "tarefa": "tarefa", "tarefas": "tarefas",
  "objetivo": "objetivo", "objetivos": "objetivos",
  "meta": "meta", "metas": "metas",
  "meta": "meta",
  "recompensa": "recompensa", "recompensas": "recompensas",
  "bonus": "bônus", "bônus": "bônus",
  "premio": "prêmio", "prêmio": "prêmio", "prêmios": "prêmios",
  "desconto": "desconto", "descontos": "descontos",
  "oferta": "oferta", "ofertas": "ofertas",
  "pedido": "pedido", "pedidos": "pedidos",
  "encomenda": "encomenda", "encomendas": "encomendas",
  "entrega": "entrega", "entregas": "entregas",
  "pagamento": "pagamento", "pagamentos": "pagamentos",
  "transferencia": "transferência", "transferência": "transferência",
  "deposito": "depósito", "depósito": "depósito",
  "saque": "saque", "saques": "saques",
  "emprestimo": "empréstimo", "empréstimo": "empréstimo",
  "investimento": "investimento", "investimentos": "investimentos",
  "lucro": "lucro", "lucros": "lucros",
  "prejuizo": "prejuízo", "prejuízo": "prejuízo",
  "risco": "risco", "riscos": "riscos",
  "sorte": "sorte",
  "sorteio": "sorteio", "sorteios": "sorteios",
  "aposta": "aposta", "apostas": "apostas",
  "premio": "prêmio",
  "leilao": "leilão", "leilão": "leilão", "leilões": "leilões",
  "lance": "lance", "lances": "lances",
  "oferta": "oferta",
  "doacao": "doação", "doação": "doação", "doações": "doações",
  "doador": "doador", "doadores": "doadores",
  "doar": "doar",

  // ── Geral / adversários / etc ──
  "horario": "horário", "horário": "horário",
  "periodo": "período", "período": "período",
  "momento": "momento", "momentos": "momentos",
  "vezes": "vezes", "vez": "vez",
  "numero": "número", "número": "número", "números": "números",
  "quantidade": "quantidade", "quantidades": "quantidades",
  "tamanho": "tamanho", "tamanhos": "tamanhos",
  "peso": "peso", "pesos": "pesos",
  "forca": "força", "força": "força", "forças": "forças",
  "defesa": "defesa", "defesas": "defesas",
  "ataque": "ataque", "ataques": "ataques",
  "velocidade": "velocidade",
  "resistencia": "resistência", "resistência": "resistência",
  "energia": "energia", "energias": "energias",
  "vida": "vida", "vidas": "vidas",
  "saude": "saúde", "saúde": "saúde",
  "fome": "fome",
  "sede": "sede",
  "temperatura": "temperatura",
  "raio": "raio", "raios": "raios",
  "tempestade": "tempestade", "tempestades": "tempestades",
  "chuva": "chuva",
  "neve": "neve",
  "frio": "frio",
  "calor": "calor",
  "vento": "vento",
  "tempestade": "tempestade",
  "gas": "gás", "gás": "gás",
  "eletricidade": "eletricidade",
  "gerador": "gerador", "geradores": "geradores",
  "radio": "rádio", "rádio": "rádio",
  "bateria": "bateria", "baterias": "baterias",
  "lampada": "lâmpada", "lâmpada": "lâmpada",
  "fogueira": "fogueira", "fogueiras": "fogueiras",
  "acampamento": "acampamento",
  "barraca": "barraca", "barracas": "barracas",
  "refugio": "refúgio", "refúgio": "refúgio",
  "abrigo": "abrigo", "abrigos": "abrigos",
  "muro": "muro", "muros": "muros",
  "cerca": "cerca", "cercas": "cercas",
  "armadilha": "armadilha", "armadilhas": "armadilhas",
  "minas": "minas",
  "explosivo": "explosivo", "explosivos": "explosivos",
  "bombas": "bombas",
  "granada": "granada", "granadas": "granadas",
  "pistola": "pistola", "pistolas": "pistolas",
  "rifle": "rifle", "rifles": "rifles",
  "escopeta": "escopeta", "escopetas": "escopetas",
  "facas": "facas",
  "espada": "espada", "espadas": "espadas",
  "machado": "machado", "machados": "machados",
  "marreta": "marreta",
  "pa": "pá", "pá": "pá",
  "enxada": "enxada",
  "picareta": "picareta",
  "martelo": "martelo", "martelos": "martelos",
  "serrote": "serrote",
  "alicate": "alicate", "alicates": "alicates",
  "chave": "chave",
  "cadeado": "cadeado", "cadeados": "cadeados",
  "parafuso": "parafuso", "parafusos": "parafusos",
  "prego": "prego", "pregos": "pregos",
  "cola": "cola",
  "fita": "fita", "fitas": "fitas",
  "corda": "corda", "cordas": "cordas",
  "tecido": "tecido", "tecidos": "tecidos",
  "couro": "couro",
  "osso": "osso", "ossos": "ossos",
  "ferro": "ferro",
  "aco": "aço", "aço": "aço",
  "ouro": "ouro",
  "prata": "prata",
  "cobre": "cobre",
  "aluminio": "alumínio", "alumínio": "alumínio",
  "borracha": "borracha",
  "vidro": "vidro",
  "papel": "papel",
  "livro": "livro", "livros": "livros",
  "revista": "revista", "revistas": "revistas",
  "jornal": "jornal",
  "mapa": "mapa",
  "bussola": "bússola", "bússola": "bússola",
  "lanterna": "lanterna", "lanternas": "lanternas",
  "isqueiro": "isqueiro",
  "fosforo": "fósforo", "fósforo": "fósforo",
  "vela": "vela", "velas": "velas",
  "tocha": "tocha", "tochas": "tochas",
  "panela": "panela", "panelas": "panelas",
  "frigideira": "frigideira",
  "garrafa": "garrafa", "garrafas": "garrafas",
  "copo": "copo", "copos": "copos",
  "prato": "prato", "pratos": "pratos",
  "colher": "colher", "colheres": "colheres",
  "faca": "faca",
  "garfo": "garfo", "garfos": "garfos",

  // ── Comida e bebida ──
  "carne": "carne", "carnes": "carnes",
  "frango": "frango",
  "peixe": "peixe", "peixes": "peixes",
  "porco": "porco",
  "boi": "boi",
  "arroz": "arroz",
  "feijao": "feijão", "feijão": "feijão",
  "batata": "batata", "batatas": "batatas",
  "tomate": "tomate", "tomates": "tomates",
  "cebola": "cebola", "cebolas": "cebolas",
  "alho": "alho",
  "cenoura": "cenoura", "cenouras": "cenouras",
  "milho": "milho",
  "trigo": "trigo",
  "acucar": "açúcar", "açúcar": "açúcar",
  "sal": "sal",
  "pimenta": "pimenta",
  "oleo": "óleo", "óleo": "óleo",
  "vinagre": "vinagre",
  "leite": "leite",
  "queijo": "queijo", "queijos": "queijos",
  "ovo": "ovo", "ovos": "ovos",
  "pao": "pão", "pão": "pão", "pães": "pães",
  "bolacha": "bolacha", "bolachas": "bolachas",
  "biscoito": "biscoito", "biscoitos": "biscoitos",
  "macarrao": "macarrão", "macarrão": "macarrão",
  "sopa": "sopa", "sopas": "sopas",
  "salada": "salada", "saladas": "saladas",
  "fruta": "fruta", "frutas": "frutas",
  "maca": "maçã", "maçã": "maçã",
  "banana": "banana", "bananas": "bananas",
  "laranja": "laranja", "laranjas": "laranjas",
  "limao": "limão", "limão": "limão",
  "uva": "uva", "uvas": "uvas",
  "morango": "morango", "morangos": "morangos",
  "abacaxi": "abacaxi",
  "manga": "manga",
  "cafe": "café", "café": "café",
  "cha": "chá", "chá": "chá",
  "suco": "suco", "sucos": "sucos",
  "cerveja": "cerveja", "cervejas": "cervejas",
  "agua": "água",

  // ── Corpo / saúde ──
  "cabeca": "cabeça", "cabeça": "cabeça",
  "braco": "braço", "braço": "braço", "braços": "braços",
  "perna": "perna", "pernas": "pernas",
  "pe": "pé", "pé": "pé", "pés": "pés",
  "mao": "mão", "mão": "mão", "mãos": "mãos",
  "dedo": "dedo", "dedos": "dedos",
  "coracao": "coração", "coração": "coração",
  "pulmao": "pulmão", "pulmão": "pulmão",
  "figado": "fígado", "fígado": "fígado",
  "estomago": "estômago", "estômago": "estômago",
  "dente": "dente", "dentes": "dentes",
  "olho": "olho", "olhos": "olhos",
  "orelha": "orelha", "orelhas": "orelhas",
  "nariz": "nariz",
  "boca": "boca",
  "pescoço": "pescoço",
  "costas": "costas",
  "barriga": "barriga",
  "pele": "pele",
  "sangue": "sangue",
  "osso": "osso",
  "fratura": "fratura", "fraturas": "fraturas",
  "ferida": "ferida", "feridas": "feridas",
  "cicatriz": "cicatriz", "cicatrizes": "cicatrizes",
  "infecao": "infecção", "infecção": "infecção",
  "virus": "vírus", "vírus": "vírus",
  "bacteria": "bactéria", "bactéria": "bactéria",
  "doenca": "doença", "doença": "doença", "doenças": "doenças",
  "veneno": "veneno", "venenos": "venenos",
  "antidoto": "antídoto", "antídoto": "antídoto",
  "vacina": "vacina", "vacinas": "vacinas",
  "antibiotico": "antibiótico", "antibiótico": "antibiótico",
  "anestesico": "anestésico", "anestésico": "anestésico",
  "analgesico": "analgésico", "analgésico": "analgésico",
  "vitamina": "vitamina", "vitaminas": "vitaminas",
  "soro": "soro",

  // ── Transporte / locomoção ──
  "carro": "carro", "carros": "carros",
  "moto": "moto", "motos": "motos",
  "bicicleta": "bicicleta", "bicicletas": "bicicletas",
  "onibus": "ônibus", "ônibus": "ônibus",
  "trem": "trem", "trens": "trens",
  "aviao": "avião", "avião": "avião", "aviões": "aviões",
  "barco": "barco", "barcos": "barcos",
  "helicoptero": "helicóptero", "helicóptero": "helicóptero",
  "tanque": "tanque", "tanques": "tanques",
  "caminhao": "caminhão", "caminhão": "caminhão",
  "combustivel": "combustível", "combustível": "combustível",
  "gasolina": "gasolina",
  "diesel": "diesel",
  "alcool": "álcool", "álcool": "álcool",
  "pneu": "pneu", "pneus": "pneus",
  "motor": "motor", "motores": "motores",
  "roda": "roda", "rodas": "rodas",
  "volante": "volante",
  "freio": "freio", "freios": "freios",
  "acelerador": "acelerador",

  // ── Construções / estruturas ──
  "construcao": "construção", "construção": "construção",
  "edificio": "edifício", "edifício": "edifício",
  "predio": "prédio", "prédio": "prédio",
  "ponte": "ponte", "pontes": "pontes",
  "tunel": "túnel", "túnel": "túnel",
  "estrada": "estrada", "estradas": "estradas",
  "rua": "rua", "ruas": "ruas",
  "avenida": "avenida", "avenidas": "avenidas",
  "praça": "praça",
  "parque": "parque", "parques": "parques",
  "floresta": "floresta", "florestas": "florestas",
  "deserto": "deserto", "desertos": "desertos",
  "rio": "rio", "rios": "rios",
  "lago": "lago", "lagos": "lagos",
  "mar": "mar",
  "oceano": "oceano", "oceanos": "oceanos",
  "montanha": "montanha", "montanhas": "montanhas",
  "vale": "vale", "vales": "vales",
  "planicie": "planície", "planície": "planície",
  "ilha": "ilha", "ilhas": "ilhas",
  "caverna": "caverna", "cavernas": "cavernas",
  "mina": "mina", "minas": "minas",
  "pais": "país", "país": "país", "países": "países",
  "cidade": "cidade", "cidades": "cidades",
  "vila": "vila", "vilas": "vilas",
  "povoado": "povoado", "povoados": "povoados",
  "hospital": "hospital", "hospitais": "hospitais",
  "escola": "escola", "escolas": "escolas",
  "igreja": "igreja", "igrejas": "igrejas",
  "loja": "loja", "lojas": "lojas",
  "mercado": "mercado", "mercados": "mercados",
  "farmacia": "farmácia", "farmácia": "farmácia",
  "delegacia": "delegacia",
  "bombeiro": "bombeiro", "bombeiros": "bombeiros",
  "policia": "polícia", "polícia": "polícia",
  "exercito": "exército", "exército": "exército",
  "governo": "governo",
  "presidente": "presidente",
  "ministerio": "ministério", "ministério": "ministério",
  "secretaria": "secretaria",
  "departamento": "departamento",
  "empresa": "empresa", "empresas": "empresas",
  "fabrica": "fábrica", "fábrica": "fábrica",
  "industria": "indústria", "indústria": "indústria",
  "comercio": "comércio", "comércio": "comércio",

  // ── Adjetivos / advérbios ──
  "rapido": "rápido", "rápido": "rápido", "rápidos": "rápidos",
  "lento": "lento", "lentos": "lentos",
  "forte": "forte", "fortes": "fortes",
  "fraco": "fraco", "fracos": "fracos",
  "novo": "novo", "nova": "nova", "novos": "novos", "novas": "novas",
  "velho": "velho", "velha": "velha", "velhos": "velhos", "velhas": "velhas",
  "jovem": "jovem", "jovens": "jovens",
  "crianca": "criança", "criança": "criança", "crianças": "crianças",
  "adulto": "adulto", "adultos": "adultos",
  "homem": "homem", "homens": "homens",
  "mulher": "mulher", "mulheres": "mulheres",
  "menino": "menino", "meninos": "meninos",
  "menina": "menina", "meninas": "meninas",
  "garoto": "garoto", "garotos": "garotos",
  "garota": "garota", "garotas": "garotas",
  "moço": "moço", "moça": "moça",
  "senhor": "senhor", "senhora": "senhora",
  "pessoa": "pessoa", "pessoas": "pessoas",
  "gente": "gente",
  "familia": "família", "família": "família",
  "pai": "pai", "mae": "mãe", "mãe": "mãe",
  "filho": "filho", "filhos": "filhos", "filha": "filha", "filhas": "filhas",
  "irmao": "irmão", "irmão": "irmão", "irmãos": "irmãos",
  "irma": "irmã", "irmã": "irmã", "irmãs": "irmãs",
  "primo": "primo", "primos": "primos",
  "prima": "prima", "primas": "primas",
  "tio": "tio", "tios": "tios",
  "tia": "tia", "tias": "tias",
  "avo": "avô", "avô": "avô", "avós": "avós",
  "avó": "avó",
  "sobrinho": "sobrinho", "sobrinhos": "sobrinhos",
  "sobrinha": "sobrinha", "sobrinhas": "sobrinhas",
  "marido": "marido",
  "esposa": "esposa",
  "namorado": "namorado", "namorada": "namorada",
  "noivo": "noivo", "noiva": "noiva",
  "casamento": "casamento",
  "divorcio": "divórcio", "divórcio": "divórcio",

  // ── Pronomes / conjunções / preposições ──
  "eu": "eu", "tu": "tu", "ele": "ele", "ela": "ela",
  "nos": "nós", "nós": "nós", "vos": "vós",
  "meu": "meu", "minha": "minha", "meus": "meus", "minhas": "minhas",
  "teu": "teu", "tua": "tua", "teus": "teus", "tuas": "tuas",
  "seu": "seu", "sua": "sua", "seus": "seus", "suas": "suas",
  "nosso": "nosso", "nossa": "nossa", "nossos": "nossos", "nossas": "nossas",
  "dele": "dele", "dela": "dela", "deles": "deles", "delas": "delas",
  "isto": "isto", "isso": "isso", "aquilo": "aquilo",
  "que": "que", "quem": "quem", "qual": "qual",
  "cujo": "cujo", "cuja": "cuja",
  "onde": "onde", "quando": "quando", "como": "como",
  "porque": "porque",
  "mas": "mas", "porem": "porém",
  "contudo": "contudo", "entretanto": "entretanto",
  "portanto": "portanto",
  "pois": "pois",
  "se": "se", "caso": "caso",
  "senao": "senão", "senão": "senão",
  "a menos que": "a menos que",
  "a fim de": "a fim de",
  "apesar de": "apesar de",
  "de acordo com": "de acordo com",
  "em vez de": "em vez de",
  "graças a": "graças a",
  "junto com": "junto com",
  "de": "de", "do": "do", "da": "da", "dos": "dos", "das": "das",
  "em": "em", "no": "no", "na": "na", "nos": "nos", "nas": "nas",
  "para": "para", "pro": "para",
  "por": "por",
  "com": "com", "comigo": "comigo",
  "sem": "sem",
  "sobre": "sobre",
  "sob": "sob",
  "entre": "entre",
  "até": "até",
  "desde": "desde",
  "durante": "durante",
  "contra": "contra",
  "perante": "perante",
  "tras": "trás", "trás": "trás",
  "via": "via",
  "ante": "ante",

  // ── Conectivos e expressões ──
  "inclusive": "inclusive",
  "excluindo": "excluindo",
  "principalmente": "principalmente",
  "especialmente": "especialmente",
  "geralmente": "geralmente",
  "normalmente": "normalmente",
  "frequentemente": "frequentemente",
  "raramente": "raramente",
  "ocasionalmente": "ocasionalmente",
  "provavelmente": "provavelmente",
  "possivelmente": "possivelmente",
  "certamente": "certamente",
  "realmente": "realmente",
  "obviamente": "obviamente",
  "exatamente": "exatamente",
  "praticamente": "praticamente",
  "basicamente": "basicamente",
  "simplesmente": "simplesmente",
  "naturalmente": "naturalmente",
  "infelizmente": "infelizmente",
  "felizmente": "felizmente",
  "curiosamente": "curiosamente",
  "surpreendentemente": "surpreendentemente",
  "legalmente": "legalmente",
  "obrigatoriamente": "obrigatoriamente",
  "opcionalmente": "opcionalmente",
  "necessariamente": "necessariamente",
  "obrigatoriamente": "obrigatoriamente",
};

// ═══════════════════════════════════════════════════════════
// ENGLISH (en) — ~1.500 entradas
// ═══════════════════════════════════════════════════════════
const en: Record<string, string> = {
  // ── Common misspellings ──
  "teh": "the", "hte": "the", "th": "the", "tha": "the",
  "adn": "and", "amd": "and", "abd": "and",
  "taht": "that", "thta": "that", "htat": "that",
  "fro": "for", "ofr": "for", "fr": "for",
  "ot": "to", "t": "to", "too": "too", "to": "to",
  "wiht": "with", "wit": "with", "wih": "with",
  "oyu": "you", "yuo": "you", "yo": "you", "yu": "you",
  "si": "is", "is": "is", "i": "I",
  "ti": "it", "ut": "it",
  "ni": "in", "im": "in",
  "on": "on", "o": "on",
  "htat": "that",
  "this": "this", "thsi": "this", "thi": "this",
  "hvae": "have", "ahve": "have", "hav": "have", "hsve": "have",
  "has": "has", "had": "had", "hda": "had",
  "was": "was", "wsa": "was",
  "were": "were", "wer": "were", "weer": "were",
  "be": "be", "been": "been", "beeen": "been",
  "being": "being", "beign": "being",
  "am": "am", "are": "are", "rare": "are",
  "do": "do", "od": "do", "does": "does", "dose": "does",
  "did": "did", "ddi": "did",
  "will": "will", "wil": "will", "wll": "will",
  "would": "would", "woudl": "would", "wuld": "would",
  "could": "could", "coudl": "could", "culd": "could",
  "should": "should", "shoudl": "should", "shuld": "should",
  "can": "can", "cna": "can",
  "may": "may", "might": "might", "migth": "might",
  "must": "must", "msut": "must",
  "shall": "shall", "shlal": "shall",
  "not": "not", "nto": "not", "no": "no",
  "but": "but", "btu": "but", "bu": "but",
  "or": "or", "ro": "or",
  "if": "if", "fi": "if",
  "then": "then", "hten": "then", "thne": "then",
  "than": "than", "htan": "than", "thna": "than",
  "so": "so", "os": "so",
  "as": "as", "sa": "as",
  "at": "at", "ta": "at",
  "by": "by", "yb": "by",
  "from": "from", "form": "from", "frm": "from",
  "up": "up", "pu": "up",
  "down": "down", "donw": "down", "dwon": "down",
  "out": "out", "otu": "out", "ou": "out",
  "off": "off", "fof": "off",
  "over": "over", "ovre": "over", "ove": "over",
  "under": "under", "unedr": "under", "undre": "under",
  "again": "again", "agian": "again", "agani": "again",
  "further": "further", "futher": "further",
  "once": "once", "noce": "once",
  "here": "here", "hre": "here", "her": "here",
  "there": "there", "thre": "there", "ther": "there", "thier": "their",
  "when": "when", "whne": "when", "wen": "when",
  "where": "where", "whre": "where", "were": "where",
  "why": "why", "wyh": "why",
  "how": "how", "ohw": "how", "ho": "how",
  "all": "all", "al": "all", "lal": "all",
  "each": "each", "eac": "each",
  "every": "every", "evry": "every", "every": "every",
  "both": "both", "boht": "both", "btoh": "both",
  "few": "few", "few": "few",
  "more": "more", "mroe": "more", "moer": "more",
  "most": "most", "mos": "most", "omst": "most",
  "other": "other", "othre": "other", "ohter": "other",
  "some": "some", "soem": "some", "smoe": "some",
  "such": "such", "suhc": "such",
  "no": "no", "on": "on",
  "any": "any", "ayn": "any", "nya": "any",
  "only": "only", "onyl": "only", "oly": "only",
  "same": "same", "smae": "same",
  "also": "also", "aslo": "also",
  "just": "just", "jsut": "just", "juts": "just",
  "very": "very", "veyr": "very", "vrey": "very",
  "often": "often", "oten": "often",
  "now": "now", "nw": "now",
  "well": "well", "wlle": "well", "wel": "well",
  "back": "back", "bakc": "back", "bck": "back",
  "even": "even", "evne": "even",
  "still": "still", "stlil": "still",
  "already": "already", "alreday": "already",
  "always": "always", "awlays": "always", "alawys": "always",
  "never": "never", "nevre": "never", "nver": "never",
  "about": "about", "abuot": "about", "abot": "about", "bout": "about",
  "after": "after", "aftre": "after", "afetr": "after",
  "before": "before", "befor": "before", "befroe": "before",
  "between": "between", "bewteen": "between", "betwen": "between",
  "through": "through", "throuhg": "through", "thorugh": "through",
  "during": "during", "durign": "during",
  "while": "while", "whiel": "while", "whle": "while",
  "until": "until", "untl": "until", "util": "until",
  "since": "since", "sice": "since",
  "because": "because", "becuase": "because", "beacuse": "because", "becaus": "because",
  "however": "however", "hoever": "however", "howver": "however",
  "although": "although", "althogh": "although", "althouh": "although",
  "though": "though", "thogh": "though", "thouh": "though",
  "either": "either", "eithe": "either", "eithr": "either",
  "neither": "neither", "niether": "neither", "nehtier": "neither",
  "whether": "whether", "wheter": "whether", "whehter": "whether",
  "these": "these", "thsee": "these", "thees": "these",
  "those": "those", "thsoe": "those", "thoes": "those",
  "which": "which", "whcih": "which", "whihc": "which",
  "what": "what", "waht": "what", "whta": "what",
  "who": "who", "whos": "who's", "hwo": "who",
  "whom": "whom", "whmo": "whom",
  "whose": "whose", "whoes": "whose",
  "many": "many", "amny": "many", "mnay": "many",
  "much": "much", "mcuh": "much", "muc": "much",
  "own": "own", "won": "own",

  // ── Common word errors ──
  "their": "their", "thier": "their", "tehir": "their",
  "theyre": "they're", "they're": "they're",
  "there": "there", "thre": "there",
  "your": "your", "yuor": "your", "yoru": "your",
  "youre": "you're", "you're": "you're",
  "its": "its", "it's": "it's", "its": "its",
  "dont": "don't", "doesn't": "doesn't", "doesnt": "doesn't",
  "didnt": "didn't", "did'nt": "didn't",
  "wont": "won't", "won't": "won't",
  "cant": "can't", "can't": "can't",
  "shouldnt": "shouldn't", "shouldn't": "shouldn't",
  "wouldnt": "wouldn't", "wouldn't": "wouldn't",
  "couldnt": "couldn't", "couldn't": "couldn't",
  "isnt": "isn't", "isn't": "isn't",
  "arent": "aren't", "aren't": "aren't",
  "wasnt": "wasn't", "wasn't": "wasn't",
  "werent": "weren't", "weren't": "weren't",
  "hasnt": "hasn't", "hasn't": "hasn't",
  "havent": "haven't", "haven't": "haven't",
  "hadnt": "hadn't", "hadn't": "hadn't",
  "im": "I'm", "i'm": "I'm",
  "ive": "I've", "i've": "I've",
  "youve": "you've", "you've": "you've",
  "theyve": "they've", "they've": "they've",
  "weve": "we've", "we've": "we've",
  "ill": "I'll", "i'll": "I'll",
  "youd": "you'd", "you'd": "you'd",
  "hed": "he'd", "he'd": "he'd",
  "shed": "she'd", "she'd": "she'd",
  "wed": "we'd", "we'd": "we'd",
  "theyd": "they'd", "they'd": "they'd",
  "lets": "let's", "let's": "let's",
  "thats": "that's", "that's": "that's",
  "whos": "who's", "who's": "who's",
  "whats": "what's", "what's": "what's",

  // ── Common vocabulary misspellings ──
  "realy": "really", "realyy": "really", "realy": "really",
  "beleive": "believe", "belive": "believe", "beleive": "believe",
  "recieve": "receive", "receve": "receive", "recevie": "receive",
  "acheive": "achieve", "acheive": "achieve", "achive": "achieve",
  "occured": "occurred", "ocurred": "occurred", "occurrd": "occurred",
  "happend": "happened", "happend": "happened",
  "begining": "beginning", "begining": "beginning",
  "definately": "definitely", "definatly": "definitely", "definitley": "definitely",
  "seperate": "separate", "seperat": "separate", "seperate": "separate",
  "occassion": "occasion", "occassion": "occasion",
  "accomodate": "accommodate", "acommodate": "accommodate",
  "accomodation": "accommodation", "acomodation": "accommodation",
  "occurrence": "occurrence", "occurrance": "occurrence",
  "adress": "address", "addres": "address",
  ``: 