/**
 * Dicionário estático de correção ortográfica para 13 idiomas.
 * Lookup O(1) — zero rede, zero bloqueio.
 * Cada entrada mapeia palavra errada → palavra correta.
 */

export type VocativeRule = [RegExp, string];

// ═══════════════════════════════════════════════════════════
// PORTUGUÊS (pt) — ~1200 entradas
// ═══════════════════════════════════════════════════════════
const pt: Record<string, string> = {
  // ── Pronomes ──
  "voce": "você", "voces": "vocês", "vocez": "você",
  "vc": "você", "vcs": "vocês", "vhc": "você",
  "teu": "teu", "tua": "tua", "seu": "seu", "sua": "sua",
  "ce": "se", "cê": "você", "nós": "nós",
  "meu": "meu", "minha": "minha", "meus": "meus", "minhas": "minhas",

  // ── Acentuação básica ──
  "nao": "não", "naum": "não", "nam": "não", "não": "não",
  "tambem": "também", "tambe": "também", "tambemm": "também", "tmb": "também",
  "porem": "porém", "porrem": "porém",
  "ninguem": "ninguém", "ninguen": "ninguém", "ngm": "ninguém",
  "alguem": "alguém", "alguen": "alguém", "algm": "alguém",
  "alem": "além", "alemm": "além",
  "ate": "até", "ateh": "até", "athé": "até",
  "ja": "já", "jah": "já", "jah": "já",
  "so": "só", "soh": "só",
  "pos": "pós", "preh": "pré", "pre": "pré",
  "util": "útil", "utill": "útil", "inutil": "inútil", "inutill": "inútil",
  "facil": "fácil", "facill": "fácil", "facilmente": "facilmente",
  "dificil": "difícil", "dificill": "difícil", "dificilmente": "dificilmente",
  "possivel": "possível", "possivell": "possível", "possivelmente": "possivelmente",
  "impossivel": "impossível",
  "necessario": "necessário", "necessaria": "necessária",
  "necessariamente": "necessariamente",
  "porke": "porque", "porqe": "porque", "porqu": "porque", "pq": "porque",
  "tao": "tão", "thau": "tão",
  "lah": "lá", "la": "lá",
  "aqui": "aqui", "aki": "aqui",
  "amanha": "amanhã", "amanhã": "amanhã",
  "manha": "manhã", "manhã": "manhã",
  "tres": "três", "tres": "três",
  "mes": "mês", "mês": "mês",
  "ceus": "céus", "ceú": "céu",
  "heroi": "herói", "herois": "heróis",
  "jornal": "jornal", "jornal": "jornal",
  "paz": "paz", "fe": "fé", "no": "nó", "nos": "nós",
  "sal": "sal", "mel": "mel", "pel": "péu", "pau": "pau",
  "avô": "avô", "avo": "avô",
  "avó": "avó",
  "vo": "vô", "ceo": "céu", "ceu": "céu",
  "noe": "nó", "nois": "nós",
  "pais": "pais", "pais": "país",
  "ruim": "ruim", "ruim": "ruim",
  "bom": "bom", "boa": "boa",
  "mau": "mau", "má": "má",
  "verdade": "verdade",
  "falso": "falso", "falsã": "falsa",
  "verdadeiro": "verdadeiro", "verdadeira": "verdadeira",
  "necessidade": "necessidade",
  "saudade": "saudade", "saudades": "saudades",
  "certeza": "certeza", "certeza": "certeza",
  "dúvida": "dúvida", "duvida": "dúvida",
  "idéia": "ideia", "idea": "ideia",
  "saúde": "saúde", "saude": "saúde",
  "doença": "doença", "doenca": "doença",
  "fraqueza": "fraqueza",
  "força": "força", "forca": "forca",
  "prazer": "prazer", "praser": "prazer",
  "azar": "azar", "azar": "azar",
  "sorte": "sorte",
  "medo": "medo",
  "raiva": "raiva", "raiva": "raiva",
  "ódio": "ódio", "odio": "ódio",
  "amor": "amor",
  "esperança": "esperança", "esperanca": "esperança",
  "carinho": "carinho",
  "tristeza": "tristeza",
  "alegria": "alegria", "alegria": "alegria",
  "feliz": "feliz", "felis": "feliz",
  "infeliz": "infeliz",
  "contente": "contente",
  "orgulho": "orgulho", "orgulho": "orgulho",
  "vergonha": "vergonha",
  "culpa": "culpa",
  "ciúme": "ciúme", "ciume": "ciúme",
  "inveja": "inveja",
  "preocupação": "preocupação", "preocupacao": "preocupação",
  "ansiedade": "ansiedade",
  "coragem": "coragem",
  "covardia": "covardia",
