# Translation dictionaries - will be injected into TranslationPopup.tsx

ES = r'''const ES: Record<string, string> = {
  "Dashboard": "Panel", "Tabela": "Tabla de precios", "Empréstimos": "Préstamos",
  "Trocas": "Intercambios", "Doadores": "Donantes", "Leilões": "Subastas",
  "Sorteios": "Sorteos", "Lotérica": "Lotería", "Investidores": "Inversores",
  "Config Trocas": "Config. Intercambios", "Compras & Vendas": "Compras y Ventas",
  "Estoque & Caixa": "Stock y Caja",
  "Carregando...": "Cargando...", "Carregando dados do banco...": "Cargando datos del banco...",
  "Carregando chat...": "Cargando chat...", "Cancelar": "Cancelar",
  "Entrar": "Entrar", "Salvar": "Guardar", "Fechar": "Cerrar",
  "Criar": "Crear", "Remover": "Eliminar", "Registrar": "Registrar",
  "Buscar...": "Buscar...", "Buscar item...": "Buscar artículo...",
  "Buscar numero ou comprador...": "Buscar número o comprador...",
  "Nome": "Nombre", "Item": "Artículo", "Quantidade": "Cantidad",
  "Tipo": "Tipo", "Data": "Fecha", "Player": "Jugador",
  "Todos": "Todos", "Admin": "Admin", "Modo visual": "Modo visual",
  "total": "total", "registros": "registros",
  "Observação": "Observación", "Opcional": "Opcional",
  "Dono": "Dueño", "Moeda": "Moneda", "Ganhador": "Ganador",
  "Vencedor": "Ganador", "Participantes": "Participantes",
  "Criado": "Creado", "Qtd": "Cant", "Inicial": "Inicial",
  "Maior": "Mayor", "Lances": "Pujas", "Taxa": "Comisión",
  "Lucro": "Ganancia", "Bruto:": "Bruto:", "Ação": "Acción",
  "Descrição": "Descripción", "Origem": "Origen",
  "Item Pagamento": "Artículo de Pago",
  "Item Pagamento (opcional)": "Artículo de Pago (opcional)",
  "Qtd Pagamento": "Cant de Pago", "Disponível": "Disponible",
  "Disponivel": "Disponible", "Posto de Trocas": "Puesto de Intercambio",
  "Sistema de gestao para sobreviventes": "Sistema de gestión para sobrevivientes",
  "Empréstimos Pendentes": "Préstamos Pendientes",
  "Empréstimos Pagos": "Préstamos Pagados",
  "Investidores Ativos": "Inversores Activos",
  "Trocas Realizadas": "Intercambios Realizados",
  "Registros no Caixa": "Registros en Caja",
  "Leilões Ativos": "Subastas Activas",
  "Sorteios Ativos": "Sorteos Activos",
  "Top 10 Doadores": "Top 10 Donantes",
  "Top 10 Investidores": "Top 10 Inversores",
  "Top 10 Contribuintes": "Top 10 Contribuyentes",
  "Estoque do Banco": "Stock del Banco",
  "Movimentos do Caixa": "Movimientos de Caja",
  "Eventos Ativos": "Eventos Activos",
  "Nenhum doador cadastrado.": "Ningún donante registrado.",
  "Nenhum investidor cadastrado.": "Ningún inversor registrado.",
  "Nenhum contribuinte ainda. Contribua reportando precos na aba Tabela!": "Ningún contribuyente aún. ¡Contribuya reportando precios en la pestaña Tabla!",
  "Nenhum item encontrado.": "Ningún artículo encontrado.",
  "Estoque vazio.": "Stock vacío.",
  "Nenhum registro ainda.": "Ningún registro aún.",
  "Nenhum registro.": "Ningún registro.",
  "desde": "desde", "contribuicoes": "contribuciones",
  "Canais": "Canales", "Salas Privadas": "Salas Privadas",
  "Geral": "General", "Atendimento": "Soporte", "Guias": "Guías",
  "Clãs": "Clanes", "Comércio": "Comercio",
  "Chat - Posto de Trocas": "Chat - Puesto de Intercambio",
  "Digite seu nome para entrar no chat.": "Introduce tu nombre para entrar al chat.",
  "Seu nome no jogo": "Tu nombre en el juego",
  "Nenhuma mensagem ainda. Seja o primeiro a conversar!": "¡Aún no hay mensajes. ¡Sé el primero en chatear!",
  "Nenhuma sala criada.": "Ninguna sala creada.",
  "Nome da sala": "Nombre de la sala",
  "Senha (opcional)": "Contraseña (opcional)",
  "Senha da sala": "Contraseña de la sala",
  "Sala Privada": "Sala Privada",
  "requer senha": "requiere contraseña",
  "Voltar": "Volver", "Hoje": "Hoy", "Ontem": "Ayer",
  "Membro": "Miembro",
  "Um território onde todos os sobreviventes são bem-vindos.": "Un territorio donde todos los sobrevivientes son bienvenidos.",
  "Sala": "Sala", "Mensagem em": "Mensaje en",
  "A sala": "La sala", "requer senha.": "requiere contraseña.",
  "Deletar sala": "Eliminar sala", "Sobreviventes": "Sobrevivientes",
  "Nenhuma mensagem ainda.": "Aún no hay mensajes.",
  "Regras:": "Reglas:", "por": "por",
  "❤️ Doadores": "❤️ Donantes",
  "Registre doações. Toda doação entra no estoque automaticamente.": "Registre donaciones. Toda donación entra al stock automáticamente.",
  "Ranking": "Ranking", "Reordenar": "Reordenar",
  "Reordenar Doadores": "Reordenar Donantes",
  "Nova Doação": "Nueva Donación",
  "Registrar Doação": "Registrar Donación",
  "Histórico": "Historial",
  "Nenhuma doação.": "Ninguna donación.",
  "Doação excluida e estoque estornado.": "Donación eliminada y stock devuelto.",
  "Não foi possível excluir a doação.": "No se pudo excluir la donación.",
  "💎 Membros Investidores": "💎 Miembros Inversores",
  "Membros Investidores": "Miembros Inversores",
  "Benefício:": "Beneficio:",
  "em empréstimos e trocas": "en préstamos e intercambios",
  "em empréstimos e trocas (vs": "en préstamos e intercambios (vs",
  "comum).": "común).",
  "comum": "común",
  "Como obter a tag?": "¿Cómo obtener la etiqueta?",
  "Ajude o banco — doando itens, fazendo trocas ou de qualquer outra forma.": "Ayude al banco — donando artículos, haciendo intercambios o de cualquier otra forma.",
  "Adicionar Investidor": "Añadir Inversor",
  "Nome do investidor": "Nombre del inversor",
  "Adicionar": "Añadir",
  "Reordenar Investidores": "Reordenar Inversores",
  "Desde": "Desde", "Ativos": "Activos",
  "Nenhum investidor.": "Ningún inversor.",
  "Digite o nome do investidor.": "Introduce el nombre del inversor.",
  "Taxa de": "Tasa de",
  "Registro de Trocas": "Registro de Intercambios",
  "Nova Troca": "Nuevo Intercambio",
  "Selecione": "Seleccionar",
  "Nenhuma tabela": "Ninguna tabla",
  "Preencha o formulário ao lado.": "Rellene el formulario al lado.",
  "sem taxa": "sin comisión",
  "Player Recebe:": "Jugador Recibe:",
  "Player entregou:": "Jugador entregó:",
  "Sai do estoque do Banco:": "Sale del stock del Banco:",
  "O item recebido entra no estoque do Banco; não há taxa nem lucro.": "El artículo recibido entra al stock del Banco; no hay comisión ni ganancia.",
  "Entra no estoque do Banco:": "Entra al stock del Banco:",
  "Entregou": "Entregó",
  "Recebeu / Entrou no estoque": "Recibió / Entró al stock",
  "Especial (0%)": "Especial (0%)",
  "Top 10 (5%)": "Top 10 (5%)",
  "Investidor (10%)": "Inversor (10%)",
  "Comum (15%)": "Común (15%)",
  "Não Contribuinte (20%)": "No Contribuyente (20%)",
  "Banco (100% — troca interna)": "Banco (100% — intercambio interno)",
  "Banco (100%)": "Banco (100%)",
  "Banco (100%):": "Banco (100%):",
  "Item que sai do estoque do Banco": "Artículo que sale del stock del Banco",
  "Item que ele entrega": "Artículo que él entrega",
  "Quantidade (em base)": "Cantidad (en base)",
  "Registrar Troca": "Registrar Intercambio",
  "Calculadora": "Calculadora",
  "Entrou:": "Entró:", "Recebeu:": "Recibió:",
  "Excluir troca e estornar estoque": "Excluir intercambio y devolver stock",
  "Troca excluída e estoque estornado.": "Intercambio excluido y stock devuelto.",
  "Não foi possível excluir a troca.": "No se pudo excluir el intercambio.",
  "🛒 Compras e Vendas": "🛒 Compras y Ventas",
  "COMPRA:": "COMPRA:",
  "Você paga → Recebe do player": "Tú pagas → Recibes del jugador",
  "VENDA:": "VENTA:",
  "Você entrega → Recebe do player": "Tú entregas → Recibes del jugador",
  "Entra": "Entra", "Sai": "Sale",
  "Paga": "Paga", "Recebe": "Recibe",
  "Compras": "Compras", "Vendas": "Ventas",
  "Nenhuma compra ou venda.": "Ninguna compra o venta.",
  "🔴 Compra": "🔴 Compra", "🟢 Venda": "🟢 Venta",
  "Obs": "Obs",
  "💰 Caixa do Banco": "💰 Caja del Banco",
  "Saída por Leilão do Banco (100%)": "Salida por Subasta del Banco (100%)",
  "Registre itens que saíram do estoque para leilões do banco.": "Registre artículos que salieron del stock para subastas del banco.",
  "Saída por Sorteio (Prêmio)": "Salida por Sorteo (Premio)",
  "Registre o prêmio que saiu do estoque quando um sorteio for finalizado.": "Registre el premio que salió del stock cuando un sorteo sea finalizado.",
  "Registro Manual": "Registro Manual",
  "ENTRADA": "INGRESO", "SAÍDA": "GASTO",
  "📦 Entrada": "📦 Ingreso", "📤 Saída": "📤 Gasto",
  "Entrada": "Ingreso", "Saída": "Gasto",
  "Estoque Atual": "Stock Actual",
  "BAIXO": "BAJO",
  "Resetar": "Resetear", "Resetar TUDO?": "¿Resetear TODO?",
  "Registrar Saída": "Registrar Salida",
  "Registrar Prêmio": "Registrar Premio",
  "Nome do jogador": "Nombre del jugador",
  "🔨 Leilões": "🔨 Subastas",
  "Como Funciona": "Cómo Funciona",
  "O leilão conta o tempo escolhido (1h a 48h).": "La subasta cuenta el tiempo elegido (1h a 48h).",
  "Qualquer pessoa pode dar lance durante o tempo.": "Cualquier persona puede ofertar durante el tiempo.",
  "Após o tempo acabar, cada novo lance adiciona": "Después de que el tiempo termine, cada nueva puja añade",
  "+1 minuto": "+1 minuto",
  "de disputa.": "de disputa.",
  "Quando o tempo de disputa acaba, o leilão vai para": "Cuando el tiempo de disputa termina, la subasta va a",
  "fila de espera": "fila de espera",
  "O admin finaliza após entregar o item e receber o pagamento.": "El admin finaliza después de entregar el artículo y recibir el pago.",
  "Novo Leilão": "Nueva Subasta", "Criar Leilão": "Crear Subasta",
  "Item (nome em pt-BR)": "Artículo (nombre en pt-BR)",
  "Valor Inicial (total do lote)": "Valor Inicial (total del lote)",
  "Origem / Taxa": "Origen / Comisión",
  "Duração": "Duración",
  "Imagem (preenche sozinho pelo nome do item)": "Imagen (se rellena solo por el nombre del artículo)",
  "Auto-preenchido": "Auto-rellenado",
  "1 minuto (teste)": "1 minuto (prueba)",
  "1 hora": "1 hora", "6 horas": "6 horas",
  "12 horas": "12 horas", "24 horas": "24 horas", "48 horas": "48 horas",
  "Fila de Espera": "Fila de Espera",
  "EM ESPERA": "EN ESPERA",
  "Nenhum leilão ativo.": "Ninguna subasta activa.",
  "Dar Lance": "Ofertar",
  "O tempo de disputa acabou.": "El tiempo de disputa terminó.",
  "Seu Nome": "Tu Nombre",
  "Valor (mín:": "Valor (mín:",
  "Dono:": "Dueño:", "Moeda:": "Moneda:",
  "Disputa final!": "¡Disputa final!",
  "Finalizar Entrega": "Finalizar Entrega",
  "Histórico de Ganhadores": "Historial de Ganadores",
  "Sorteios": "Sorteos",
  "Admin cria sorteio com": "Admin crea sorteo con",
  "item e duracao": "artículo y duración",
  "Qualquer membro participa com seu nome.": "Cualquier miembro participa con su nombre.",
  "Timer acaba": "El temporizador termina",
  "ganhador": "ganador", "sorteado": "sorteado",
  "Novo Sorteio": "Nuevo Sorteo",
  "Duracao (min)": "Duración (min)",
  "Nenhum.": "Ninguno.",
  "Participar": "Participar", "Sortear": "Sortear",
  "Seu nome": "Tu nombre",
  "Historico de Ganhadores": "Historial de Ganadores",
  "Data do Sorteio": "Fecha del Sorteo",
  "Todos os Participantes": "Todos los Participantes",
  "Nenhum": "Ninguno",
  "Encerrado": "Cerrado", "ENCERRADO": "CERRADO",
  "Quantidade:": "Cantidad:",
  "Lotérica Ativa": "Lotería Activa",
  "Vendas abertas": "Ventas abiertas",
  "Sorteio realizado": "Sorteo realizado",
  "Finalizada": "Finalizada",
  "Configurando": "Configurando",
  "Vendidos": "Vendidos", "Disponiveis": "Disponibles",
  "Arrecadado Total": "Total Recaudado",
  "Premio": "Premio",
  "Min. acumulado": "Mín. acumulado",
  "Taxa Banco (20%)": "Comisión Banco (20%)",
  "Credita ao finalizar": "Se acredita al finalizar",
  "Calculo do Premio": "Cálculo del Premio",
  "80% arrecadado": "80% recaudado",
  "Minimo original": "Mínimo original",
  "Min. efetivo": "Mín. efectivo",
  "Premio = maior entre 80% do arrecadado e o minimo efetivo": "Premio = máximo entre 80% de lo recaudado y el mínimo efectivo",
  "Teve Ganhador!": "¡Hay Ganador!",
  "Ninguem acertou - Premio acumulou!": "¡Nadie acertó - Premio acumulado!",
  "Ninguem acertou - Premio acumulou": "Nadie acertó - Premio acumulado",
  "Numero": "Número",
  "Numero (1-1000)": "Número (1-1000)",
  "Ganhador:": "Ganador:", "Premio:": "Premio:",
  "Nao foi vendido": "No fue vendido",
  "acumulados": "acumulados",
  "20% das vendas": "20% de las ventas",
  "creditado no estoque.": "acreditado al stock.",
  "Finalizar Lotérica": "Finalizar Lotería",
  "Vender Numero": "Vender Número",
  "Nome do Comprador": "Nombre del Comprador",
  "Vender": "Vender",
  "Realizar Sorteio": "Realizar Sorteo",
  "As vendas encerraram. Sorteie para definir o ganhador.": "Las ventas terminaron. Sortee para definir el ganador.",
  "Nenhum numero vendido! Nao e possivel sortear.": "¡Ningún número vendido! No es posible sortear.",
  "Nenhum numero.": "Ningún número.",
  "Nenhuma lotérica ativa. Crie uma nova acima.": "Ninguna lotería activa. Cree una nueva arriba.",
  "Nenhuma lotérica ativa no momento.": "Ninguna lotería activa en el momento.",
  "Historico de Sorteios": "Historial de Sorteos",
  "Premio Min.": "Premio Mín.",
  "Acumulado Anterior": "Acumulado Anterior",
  "acumulado": "acumulado",
  "Nova Lotérica": "Nueva Lotería",
  "Configurar Lotérica": "Configurar Lotería",
  "Criar Lotérica": "Crear Lotería",
  "Valor/Numero": "Valor/Número",
  "Premio Minimo": "Premio Mínimo",
  "Duracao Vendas (min)": "Duración Ventas (min)",
  "1000 numeros": "1000 números",
  "20%": "20%", "80%": "80%",
  "preco fixo por numero.": "precio fijo por número.",
  "das vendas vai pro banco": "de las ventas va al banco",
  "vai pro premio": "va al premio",
  "Premio =": "Premio =",
  "maior entre 80% das vendas e o minimo": "máximo entre 80% de las ventas y el mínimo",
  "Se ninguem acertar, o premio": "Si nadie acierta, el premio",
  "vira o novo minimo": "se convierte en el nuevo mínimo",
  "da proxima.": "del próximo.",
  "So reseta quando sair um": "Solo se reinicia cuando salga un",
  "comes out!": "¡sale!",
  "Numero sorteado:": "Número sorteado:",
  "- Ganhador:": "- Ganador:", "- Premio:": "- Premio:",
  "- Nao foi vendido -": "- No fue vendido -",
  "das vendas vai pro banco,": "de las ventas va al banco,",
  "Regras do Banco": "Reglas del Banco",
  "Membro Especial": "Miembro Especial",
  "Top 10 Investidor": "Top 10 Inversor",
  "Investidor": "Inversor",
  "Membro Comum": "Miembro Común",
  "Não Contribuinte": "No Contribuyente",
  "sem acréscimo": "sin recargo",
  "de acréscimo": "de recargo",
  "Calculadora de Empréstimo": "Calculadora de Préstomo",
  "Dias de Atraso": "Días de Atraso",
  "Total a Devolver": "Total a Devolver",
  "itens": "artículos",
  "Prazo: 24 horas. Após: +1% de juros por dia.": "Plazo: 24 horas. Después: +1% de interés por día.",
  "Novo Empréstimo": "Nuevo Préstomo",
  "Pendentes": "Pendientes", "Pagos": "Pagados",
  "Nenhum empréstimo pendente.": "Ningún préstomo pendiente.",
  "Pendente": "Pendiente", "Pago": "Pagado", "Atrasado": "Atrasado",
  "Pagar": "Pagar",
  "Valor a cobrar:": "Valor a cobrar:",
  "Vencimento:": "Vencimiento:",
  "Registrar Pagamento": "Registrar Pago",
  "Item do Pagamento": "Artículo del Pago",
  "Confirmar Pagamento": "Confirmar Pago",
  "Empréstimo atrasado - Juros já incluídos": "Préstomo atrasado - Intereses ya incluidos",
  "Item:": "Artículo:", "Quantidade:": "Cantidad:",
  "Top 10 Investidor (5%)": "Top 10 Inversor (5%)",
  "Alta": "Alta", "Media": "Media", "Baixa": "Baja",
  "Incomum": "Poco común", "Raro": "Raro", "Lendario": "Legendario",
  "Demanda": "Demanda", "Raridade": "Rareza",
  "Preço (Aço)": "Precio (Acero)",
  "Preço (Cimento)": "Precio (Cemento)",
  "Tabela de Precos": "Tabla de Precios",
  "Reportar Precos": "Reportar Precios",
  "Guia da Tabela de Precos": "Guía de la Tabla de Precios",
  "Gerenciar Itens": "Gestionar Artículos",
  "Login Admin": "Login Admin",
  "Verificando...": "Verificando...",
  "Backup": "Backup", "Gerando...": "Generando...",
  "Modo Admin ativado!": "¡Modo Admin activado!",
  "Senha incorreta!": "¡Contraseña incorrecta!",
  "Digite a senha de administrador para acessar o modo Admin.": "Introduce la contraseña de administrador para acceder al modo Admin.",
  "Digite a senha de admin!": "¡Introduce la contraseña de admin!",
  "Entre no modo Admin para baixar o backup.": "Entre al modo Admin para descargar el backup.",
  "Não foi possível gerar o backup.": "No se pudo generar el backup.",
  "Backup baixado com sucesso!": "¡Backup descargado con éxito!",
  "Erro ao baixar o backup.": "Error al descargar el backup.",
  "Traduzir o Site": "Traducir el Sitio",
  "Selecione seu idioma": "Seleccione su idioma",
  "Traduzir para": "Traducir a",
  "Continuar em Português": "Continuar en Portugués",
  "Deletar mensagem?": "¿Eliminar mensaje?",
  "Remover?": "¿Eliminar?",
  "Registro adicionado!": "¡Registro añadido!",
  "Ordem atualizada!": "¡Orden actualizada!",
  "Lotérica criada!": "¡Lotería creada!",
  "Sorteio criado!": "¡Sorteo creado!",
  "Participando!": "¡Participando!",
  "Preencha os obrigatórios.": "Rellene los obligatorios.",
  "Preencha todos os campos.": "Rellene todos los campos.",
  "Preencha nome e valor.": "Rellene nombre y valor.",
  "Preencha o item e a quantidade.": "Rellene el artículo y la cantidad.",
  "Preencha todos.": "Rellene todo.",
  "Preencha valor e moeda.": "Rellene valor y moneda.",
  "Numero e nome obrigatorios.": "Número y nombre obligatorios.",
  "Numero entre 1 e 1000.": "Número entre 1 y 1000.",
  "Sem loterica ativa.": "Sin lotería activa.",
  "Ja existe loterica ativa. Finalize a atual.": "Ya existe lotería activa. Finalice la actual.",
  "Digite seu nome.": "Introduce tu nombre.",
  "Digite um nome.": "Introduce un nombre.",
  "Nome da sala é obrigatório.": "El nombre de la sala es obligatorio.",
  "Preencha nome, item e quantidade.": "Rellene nombre, artículo y cantidad.",
  "Preencha o item, quantidade e ganhador.": "Rellene artículo, cantidad y ganador.",
  "Imagem não carregou": "La imagen no cargó",
  "(abrir)": "(abrir)",
  "Carregando imagem...": "Cargando imagen...",
  "Imagem compartilhada": "Imagen compartida",
  "Clique para expandir": "Clic para expandir",
  "- clique para reproduzir": "- clic para reproducir",
  "Vídeo do YouTube": "Vídeo de YouTube",
  "Abrir no YouTube": "Abrir en YouTube",
  "Configuração de Tabelas de Troca": "Configuración de Tablas de Intercambio",
  "Nova Regra": "Nueva Regla",
  "Se o player der...": "Si el jugador da...",
  "Ele recebe...": "El recibe...",
  "Base": "Base", "Proporção": "Proporción",
  "Resultado": "Resultado", "Ações": "Acciones",
  "Nenhuma regra configurada.": "Ninguna regla configurada.",
  "Como funciona:": "Cómo funciona:",
  "As regras são usadas na aba \"Trocas\" para calcular automaticamente. Taxas: 15% comum / 10% investidor.": "Las reglas se usan en la pestaña \"Intercambios\" para calcular automáticamente. Comisiones: 15% común / 10% inversor.",
  "Tabela adicionada!": "¡Tabla añadida!",
  "Reportar": "Reportar",
  "Editar": "Editar", "Restaurar": "Restaurar",
  "Adicionar Item": "Añadir Artículo",
  "Removidos": "Eliminados",
  "Relatório": "Informe",
  "Bem-vindo ao Chat Geral. Espaço para todos conversarem, fazerem amizades, compartilharem experiências e trocarem conhecimentos sobre Day R Survival. Trate todos com respeito.": "Bienvenido al Chat General. Espacio para que todos conversen, hagan amigos, compartan experiencias e intercambien conocimientos sobre Day R Survival. Trate a todos con respeto.",
  "Espaço para contato direto com a administração. Tire dúvidas, solicite ajuda, reporte problemas, denuncie comportamentos ou envie sugestões.": "Espacio para contacto directo con la administración. Saque dudas, solicite ayuda, reporte problemas, denuncie comportamientos o envíe sugerencias.",
  "Espaço para compartilhar guias, dicas de sobrevivência, estratégias de combate, rotas de exploração e tutoriais sobre Day R Survival.": "Espacio para compartir guías, consejos de supervivencia, estrategias de combate, rutas de exploración y tutoriales sobre Day R Survival.",
  "Espaço para clãs se apresentarem, divulgarem recrutamentos, fazerem parcerias e compartilharem eventos. Respeito entre todos.": "Espacio para que los clanes se presenten, anuncien reclutamientos, hagan asociaciones y compartan eventos. Respeto entre todos.",
  "Espaço para comprar, vender ou trocar itens. Anuncie ofertas, procure recursos específicos e negocie com educação.": "Espacio para comprar, vender o intercambiar artículos. Anuncie ofertas, busque recursos específicos y negocie con educación.",
  "Respeite todos os participantes": "Respete a todos los participantes",
  "Sem spam ou flood": "Sin spam ni flood",
  "Rivalidades ficam no jogo": "Las rivalidades se quedan en el juego",
  "Pedir/Oferecer ajuda": "Pedir/Offercer ayuda",
  "Compartilhar dicas": "Compartir consejos",
  "Seja claro no problema": "Sea claro en el problema",
  "Aguarde atendimento": "Espere atención",
  "Admin responde com discrição": "El admin responde con discreción",
  "Não use pra conversas gerais": "No lo use para charlas generales",
  "Conteúdo relacionado ao jogo": "Contenido relacionado al juego",
  "Informe a versão do guia": "Indique la versión de la guía",
  "Evite informações sem confirmação": "Evite información sin confirmación",
  "Não repita conteúdos": "No repita contenidos",
  "Respeite o trabalho dos autores": "Respete el trabajo de los autores",
  "Proibido atacar outros clãs": "Prohibido atacar otros clanes",
  "Sem rivalidades no chat": "Sin rivalidades en el chat",
  "Divulgue sem spam": "Anuncie sin spam",
  "Jogadores sem clã são bem-vindos": "Jugadores sin clan son bienvenidos",
  "Faça parcerias": "Haga asociaciones",
  "Seja claro nas ofertas": "Sea claro en las ofertas",
  "Respeite os acordos": "Respete los acuerdos",
  "Sem spam de anúncios": "Sin spam de anuncios",
  "Negocie com honestidade": "Negocie con honestidad",
  "Trocas são por conta dos participantes": "Los intercambios son por cuenta de los participantes",
  "Taxas: 15% comum / 10% investidor.": "Comisiones: 15% común / 10% inversor.",
  "Preencha os campos obrigatórios.": "Rellene los campos obligatorios.",
  "Ex: Moeda": "Ej: Moneda",
  "Ex: Katana": "Ej: Katana",
  "Ex: Compra": "Ej: Compra",
  "Ex: Aco": "Ej: Acero",
  "100%": "100%",
  "nº": "nº",
};
'''

print(f"ES dict length: {ES.count('"') // 2}")
print("ES dict generated")
