import json
import re

with open('/home/z/my-project/src/data/prices.json', 'r') as f:
    data = json.load(f)

# Items that are clearly still in English
english_items = []
for cat in data['categories']:
    for item in cat['items']:
        name = item['name']
        # Detect names that contain English words (multi-word with spaces, or common English patterns)
        # Simple heuristic: if name has spaces and looks like English phrase
        words = name.split()
        if len(words) >= 2:
            # Check for common English words in multi-word names
            eng_indicators = ['the', 'and', 'for', 'with', 'from', 'energy', 'drink', 'water',
                'mold', 'meat', 'cake', 'egg', 'rice', 'pasta', 'corn', 'milk', 'fish',
                'soup', 'bread', 'salt', 'sugar', 'sauce', 'oil', 'tea', 'coffee',
                'wine', 'beer', 'juice', 'cooked', 'raw', 'dirty', 'clean', 'rotten',
                'dried', 'fried', 'roasted', 'boiled', 'canned', 'fresh', 'frozen',
                'radioactive', 'contaminated', 'spooky', 'chinese', 'easter', 'blood',
                'medicinal', 'medical', 'first', 'aid', 'kit', 'set', 'part', 'piece',
                'metal', 'wood', 'stone', 'iron', 'steel', 'copper', 'cloth', 'leather',
                'rubber', 'plastic', 'paper', 'glass', 'rope', 'wire', 'nail', 'screw',
                'bolt', 'spring', 'gear', 'wheel', 'engine', 'motor', 'fuel', 'gas',
                'bullet', 'shell', 'cartridge', 'gun', 'rifle', 'pistol', 'shotgun',
                'armor', 'helmet', 'boots', 'gloves', 'jacket', 'shirt', 'pants',
                'hat', 'mask', 'backpack', 'bag', 'belt', 'bandage', 'antibiotic',
                'vitamin', 'poison', 'acid', 'explosive', 'bomb', 'grenade', 'mine',
                'trap', 'fence', 'door', 'window', 'wall', 'floor', 'roof', 'table',
                'chair', 'bed', 'shelf', 'locker', 'safe', 'box', 'chest', 'crate',
                'barrel', 'bucket', 'bottle', 'cup', 'plate', 'pot', 'pan', 'fork',
                'knife', 'axe', 'hammer', 'saw', 'shovel', 'pickaxe', 'crowbar',
                'wrench', 'pliers', 'drill', 'file', 'chisel', 'tape', 'glue',
                'paint', 'brush', 'tincan', 'tuna', 'salmon', 'shrimp', 'crab',
                'mushroom', 'berry', 'apple', 'pear', 'grape', 'cherry', 'lemon',
                'orange', 'banana', 'peach', 'plum', 'melon', 'pumpkin', 'cabbage',
                'carrot', 'potato', 'tomato', 'onion', 'garlic', 'pepper', 'herb',
                'tobacco', 'cigar', 'cigarette', 'chocolate', 'candy', 'honey',
                'butter', 'cheese', 'cream', 'yogurt', 'kefir', 'kumis',
                'cotton', 'silk', 'wool', 'thread', 'needle', 'button', 'zipper',
                'match', 'candle', 'lamp', 'flashlight', 'battery', 'radio',
                'compass', 'map', 'book', 'newspaper', 'photo', 'mirror',
                'clock', 'watch', 'thermometer', 'barometer', 'scale',
                'wolf', 'bear', 'dog', 'cat', 'rat', 'snake', 'spider',
                'scorpion', 'fly', 'mosquito', 'bee', 'wasp', 'ant',
                'cricket', 'frog', 'turtle', 'rabbit', 'deer', 'boar', 'horse',
                'feather', 'bone', 'horn', 'tusk', 'fur', 'pelt', 'hide',
                'skin', 'scale', 'shell', 'claw', 'fang', 'tooth', 'beak',
                'wing', 'tail', 'fin', 'gill', 'tongue', 'eye', 'ear', 'nose',
                'mouth', 'lip', 'heart', 'liver', 'kidney', 'brain', 'lung',
                'intestine', 'stomach', 'blood', 'urine', 'feces', 'vomit',
                'saliva', 'sweat', 'tear', 'milk', 'sperm', 'egg', 'embryo',
                'larva', 'pupa', 'cocoon', 'web', 'nest', 'hive', 'burrow',
                'den', 'cave', 'tunnel', 'bridge', 'road', 'path', 'trail',
                'river', 'lake', 'sea', 'ocean', 'swamp', 'forest', 'desert',
                'mountain', 'hill', 'valley', 'plain', 'field', 'meadow',
                'garden', 'farm', 'ranch', 'village', 'town', 'city', 'camp',
                'base', 'bunker', 'shelter', 'house', 'building', 'factory',
                'hospital', 'school', 'shop', 'market', 'bank', 'office',
                'tower', 'wall', 'gate', 'fence', 'barrier', 'barricade',
                'crystal', 'diamond', 'emerald', 'ruby', 'sapphire', 'amethyst',
                'topaz', 'opal', 'pearl', 'coral', 'amber', 'jade', 'obsidian',
                'granite', 'marble', 'basalt', 'sandstone', 'limestone', 'slate',
                'quartz', 'mica', 'clay', 'chalk', 'coal', 'charcoal',
                'sulfur', 'phosphorus', 'nitrogen', 'oxygen', 'hydrogen', 'helium',
                'carbon', 'silicon', 'uranium', 'plutonium', 'radium', 'thorium',
                'lead', 'tin', 'zinc', 'nickel', 'chromium', 'manganese',
                'titanium', 'tungsten', 'cobalt', 'molybdenum', 'vanadium',
                'silver', 'gold', 'platinum', 'palladium', 'iridium',
                'aluminum', 'magnesium', 'calcium', 'sodium', 'potassium',
                'circuit', 'chip', 'processor', 'sensor', 'switch', 'button',
                'keyboard', 'screen', 'display', 'monitor', 'speaker', 'microphone',
                'camera', 'lens', 'telescope', 'microscope', 'binoculars',
                'antenna', 'satellite', 'radar', 'sonar', 'gps', 'laser',
                'solar', 'panel', 'cell', 'battery', 'generator', 'transformer',
                'cable', 'plug', 'socket', 'outlet', 'adapter', 'converter',
                'inverter', 'charger', 'controller', 'module', 'unit', 'system',
                'device', 'machine', 'tool', 'instrument', 'equipment', 'apparatus',
                'mechanism', 'mechanism', 'structure', 'construction', 'material',
                'component', 'element', 'part', 'piece', 'fragment', 'section',
                'segment', 'portion', 'portion', 'quantity', 'amount', 'number',
                'type', 'kind', 'sort', 'variety', 'class', 'category',
                'level', 'rank', 'grade', 'quality', 'standard', 'model',
                'version', 'edition', 'variant', 'modification', 'upgrade',
                'repair', 'fix', 'patch', 'restore', 'recover', 'heal', 'cure',
                'damage', 'hurt', 'wound', 'injury', 'pain', 'disease', 'illness',
                'sickness', 'infection', 'poisoning', 'radiation', 'contamination',
                'hunger', 'thirst', 'exhaustion', 'fatigue', 'stress', 'fear',
                'anger', 'sadness', 'happiness', 'confidence', 'morale',
                'craft', 'build', 'create', 'make', 'produce', 'manufacture',
                'gather', 'collect', 'harvest', 'mine', 'fish', 'hunt',
                'cook', 'bake', 'roast', 'fry', 'boil', 'grill', 'steam',
                'preserve', 'store', 'keep', 'hold', 'carry', 'transport',
                'buy', 'sell', 'trade', 'exchange', 'swap', 'barter',
                'find', 'search', 'explore', 'discover', 'investigate',
                'read', 'write', 'draw', 'paint', 'carve', 'sculpt',
                'play', 'sing', 'dance', 'fight', 'shoot', 'throw',
                'run', 'walk', 'climb', 'swim', 'fly', 'drive', 'ride',
                'open', 'close', 'lock', 'unlock', 'break', 'fix', 'repair',
                'attach', 'detach', 'connect', 'disconnect', 'combine', 'separate',
                'fill', 'empty', 'pour', 'spill', 'leak', 'block', 'unblock',
                'boost', 'reduce', 'increase', 'decrease', 'improve', 'worsen',
                'manual', 'automatic', 'electric', 'electronic', 'digital',
                'analog', 'mechanical', 'thermal', 'chemical', 'biological',
                'nuclear', 'atomic', 'magnetic', 'optical', 'acoustic',
                'small', 'medium', 'large', 'tiny', 'huge', 'giant',
                'light', 'heavy', 'soft', 'hard', 'sharp', 'blunt',
                'fast', 'slow', 'strong', 'weak', 'tough', 'brittle',
                'hot', 'cold', 'warm', 'cool', 'wet', 'dry',
                'new', 'old', 'young', 'ancient', 'modern', 'future',
                'good', 'bad', 'better', 'worse', 'best', 'worst',
                'common', 'uncommon', 'rare', 'epic', 'legendary',
                'simple', 'complex', 'basic', 'advanced', 'superior',
                'starter', 'beginner', 'intermediate', 'expert', 'master',
                'white', 'black', 'red', 'blue', 'green', 'yellow',
                'brown', 'gray', 'grey', 'orange', 'pink', 'purple',
                'gold', 'silver', 'bronze', 'copper', 'iron', 'steel',
                'wooden', 'stone', 'metal', 'leather', 'cloth', 'rubber',
                'military', 'civilian', 'medical', 'scientific', 'industrial',
                'domestic', 'outdoor', 'indoor', 'portable', 'stationary',
                'single', 'double', 'triple', 'quad', 'multi',
                'half', 'quarter', 'third', 'fifth', 'tenth',
                'one', 'two', 'three', 'four', 'five',
                'six', 'seven', 'eight', 'nine', 'ten',
                'first', 'second', 'third', 'fourth', 'fifth',
                'primary', 'secondary', 'tertiary', 'final', 'ultimate',
                'left', 'right', 'top', 'bottom', 'front', 'back',
                'upper', 'lower', 'inner', 'outer', 'central', 'side',
                'north', 'south', 'east', 'west',
                'spring', 'summer', 'autumn', 'winter',
                'dawn', 'day', 'dusk', 'night',
                'morning', 'afternoon', 'evening', 'midnight',
                ' monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday',
                'january', 'february', 'march', 'april', 'may', 'june',
                'july', 'august', 'september', 'october', 'november', 'december']
            
            lower_words = [w.lower() for w in words]
            eng_count = sum(1 for w in lower_words if w in eng_indicators)
            # If more than half the words are English indicators, likely English name
            if len(lower_words) > 1 and eng_count >= len(lower_words) * 0.6:
                english_items.append({'id': item['id'], 'name': name, 'category': cat['name']})

print(f'Total items likely still in English: {len(english_items)}')
for item in english_items:
    print(f"  {item['id']}: \"{item['name']}\" [{item['category']}]")
