#!/usr/bin/env python3
"""Translate ALL remaining English item names to PT-BR."""
import json

with open('/home/z/my-project/src/data/prices.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

translations = {
    # ===== Sementes, Ervas e Cogumelos =====
    'mysterious_fruit_seeds': 'Sementes de Fruta Misteriosa',
    'potato_seeds': 'Sementes de Batata',
    'vegetable_seeds': 'Sementes de Legumes',
    
    # ===== Comida, Bebidas e Ingredientes (remaining English) =====
    'condensed_milk': 'Leite Condensado',
    'fatty_meat': 'Carne Gordurosa',
    'flatbread': 'Pao Achatado',
    'gingerbread': 'Bolo de Gengibre',
    'grilled_meat': 'Carne Grelhada',
    'homemade_wine': 'Vinho Artesanal',
    'kholodets': 'Kholodets',
    'ksyukha': 'Ksyukha',
    'mukha': 'Mukha',
    'mulled_wine': 'Vinho Quente Especiado',
    'mutant_meat': 'Carne de Mutante',
    'mysterious_fruit': 'Fruta Misteriosa',
    'nettle': 'Urtiga',
    'pasta_with_ground_beef': 'Massa com Carne Moida',
    'peking_duck': 'Pato Laqueado',
    'pepsi': 'Pepsi',
    'pickled_vegetables': 'Legumes em Conserva',
    'pilaf': 'Pilaf',
    'potato_pancakes': 'Panquecas de Batata',
    'rice_bun': 'Pao de Arroz',
    'rich_chowder': 'Caldo Rico',
    'rotten_vegetables': 'Legumes Podres',
    'russian_cigarettes': 'Cigarros Russos',
    'salted_fish': 'Peixe Salgado',
    'salted_meat': 'Carne Salgada',
    'sausage': 'Salsicha',
    'shawarma': 'Churrasco Grego',
    'stearin': 'Estearina',
    'strange_mushroom_black': 'Cogumelo Estranho (Preto)',
    'strange_mushroom_blue': 'Cogumelo Estranho (Azul)',
    'strange_mushroom_green': 'Cogumelo Estranho (Verde)',
    'strange_mushroom_light_blue': 'Cogumelo Estranho (Azul Claro)',
    'strange_mushroom_red': 'Cogumelo Estranho (Vermelho)',
    'strange_mushroom_violet': 'Cogumelo Estranho (Violeta)',
    'strange_mushroom_white': 'Cogumelo Estranho (Branco)',
    'strange_mushroom_yellow': 'Cogumelo Estranho (Amarelo)',
    'strawberry': 'Morango',
    'sushi': 'Sushi',
    'toxic_water': 'Agua Toxica',
    'treats': 'Guloseimas',
    'cranberry': 'Oxicoco',
    
    # ===== Materiais e Componentes =====
    'diy_nets': 'Redes Artesanais',
    'silage_mincer': 'Moiðor de Silagem',
    'abakan': 'Abakan',
    'all_in': 'All-In',
    'alphacelone': 'Alphacelone',
    'antelope': 'Antilope',
    'barrel': 'Barril',
    'biathlon_84': 'Biathlon-84',
    'bingo': 'Bingo',
    'bioblocade_inhaler': 'Inalador Bioblocade',
    'blackjack': 'Blackjack',
    'blank': 'Espacador',
    'bryocarm': 'Bryocarm',
    'bye_bye_rad': 'Bye-Bye Rad',
    'c_3_cologne': 'Colonia C-3',
    'cpe_leader': 'CPE Leader',
    'black_coal': 'Carvao Negro',
    'catalysis_e': 'Catalysis-E',
    'wax': 'Cera',
    'chainsaw': 'Motosserra',
    'chainsaw_motor': 'Motor de Motosserra',
    'chinese_fireworks': 'Fogos de Artificio Chineses',
    'cho_ko_nu': 'Cho-ko-nu',
    'collector': 'Colecionador',
    'crouching_tiger': 'Tigre Agachado',
    'cybermitten': 'Cybermitten',
    'degtyar': 'Degtyar',
    'caustic_distillate': 'Destilado Caustico',
    'diluted_spirits': 'Alcool Diluido',
    'double_barrel': 'Estopa',
    'dragon_s_roar': 'Rugido do Dragao',
    'ea_spectrum': 'EA Spectrum',
    'erebus_273': 'Erebus-273',
    'spice': 'Especiaria',
    'expeditionary_ration': 'Racao de Expedicao',
    'fatum_e_93': 'FATUM E-93',
    'fear': 'Fear',
    'fire_brick': 'Tijolo Refratario',
    'fist_of_the_sky': 'Punho do Ceo',
    'flesh': 'Carne',
    'flying_spaghetti_monster': 'Monstro Espaguete Voador',
    'forward_s_stick': 'Bastao do Forward',
    'gaz_24_broken': 'GAZ-24 (Quebrado)',
    'gangster': 'Gangster',
    'gasoline_engine': 'Motor a Gasolina',
    'gehenna': 'Gehenna',
    'gigawattor': 'Gigawattor',
    'glue_tape': 'Fita Adesiva',
    'grouse': 'Galo-da-serra',
    'guandao': 'Guandao',
    'healing_salve': 'Balsamo Curativo',
    'hidden_dragon': 'Dragao Oculto',
    'high_performance_capacitor': 'Capacitor de Alta Performance',
    'ir_190': 'IR-190',
    'iceberg': 'Iceberg',
    'icicle_thrower': 'Lancador de Estalactites',
    'infected_rusk': 'Biscoito Duro Infectado',
    'infernal_prophet': 'Profeta Infernal',
    'insulating_tape': 'Fita Isolante',
    'iron_felix': 'Felix de Ferro',
    'iron_pipe': 'Cano de Ferro',
    'joker': 'Coringa',
    'joy': 'Joy',
    'kalash_m': 'Kalash-M',
    'kalash_s': 'Kalash-S',
    'kamaz_broken': 'KamAZ (Quebrado)',
    'first_aid_kit': 'Kit de Primeiros Socorros',
    'can': 'Lata',
    'law_guardian': 'Guardiao da Lei',
    'firewood': 'Lenha',
    'lymph': 'Linfa',
    'lotus_of_death': 'Lotus da Morte',
    'makar': 'Makar',
    'mauser': 'Mauser',
    'mayhem': 'Mayhem',
    'midas': 'Midas',
    'titanium_ore': 'Minerio de Titanio',
    'mining_permit': 'Licenca de Mineracao',
    'mosinka': 'Mosinka',
    'motorcycle_spare_parts': 'Pecas Sobressalentes de Moto',
    'murmur': 'Murmurio',
    'nagant': 'Nagant',
    'olivier_salad': 'Salada Olivier',
    'fresh_bones': 'Ossos Frescos',
    'pas_weaver': 'PAS Weaver',
    'pk_7_62_kraken': 'PK 7.62 Kraken',
    'pps_43_broken': 'PPS-43 (Quebrado)',
    'ppsh_41_broken': 'PPSh-41 (Quebrado)',
    'flint': 'Pederneira',
    'pepperbox': 'Pepperbox',
    'pill_of_immortality': 'Pilula da Imortalidade',
    'tires': 'Pneus',
    'posh': 'Posh',
    'chitin': 'Quitina',
    'rpg_vesuvius': 'Lancador RPG Vesuvio',
    'rpk_74_broken': 'RPK-74 (Quebrado)',
    'rpo_m_eye_of_the_storm': 'RPO-M Olho da Tempestade',
    'ration_pack': 'Racao',
    'raw_fatback': 'Toucinho Cru',
    'rawhide': 'Couro Cru',
    'king_of_jokers': 'Rei dos Coringas',
    'revenge': 'Vinganca',
    'rusted_saucepan': 'Panela Enferrujada',
    'sr_delirium': 'SR Delirium',
    'svt_40_broken': 'SVT-40 (Quebrado)',
    'soap': 'Sabao',
    'sabre': 'Sabre',
    'sanguinary_masha': 'Masha Sanguinaria',
    'saucepan': 'Panela',
    'schmeisser': 'Schmeisser',
    'shmel': 'Shmel',
    'shock_bludgeon': 'Tacapao de Choque',
    'sipuha': 'Sipuha',
    'skorpion': 'Skorpion',
    'smoked_fatback': 'Toucinho Defumado',
    'smuggler_s_flask': 'Frasco do Contrabandista',
    'sniper_s_mosin': 'Mosin do Sniper',
    'ice_cream': 'Sorvete',
    'spare_weapon_parts': 'Pecas Sobressalentes de Arma',
    'stake_thrower': 'Lancador de Estacas',
    'stecha': 'Stecha',
    'scrap_metal': 'Sucata Metalica',
    'aluminum_scrap': 'Sucata de Aluminio',
    'copper_scrap': 'Sucata de Cobre',
    'sudayev': 'Sudayev',
    'survivor_s_cache': 'Cache do Sobrevivente',
    'svetka': 'Svetka',
    'svyokr': 'Svyokr',
    'tt_33_broken': 'TT-33 (Quebrado)',
    'tanned_leather': 'Couro Curtido',
    'tanning_mixture': 'Mistura de Curtimento',
    'termite': 'Termite',
    'thick_hide': 'Pele Grossa',
    'thick_leather': 'Couro Grosso',
    'toxigen': 'Toxigen',
    'rags': 'Trapos',
    'trophy_cognac': 'Conhaque Trofeu',
    'uaz_452_broken': 'UAZ-452 (Quebrado)',
    'uaz_469_broken': 'UAZ-469 (Quebrado)',
    'ulcer_amr': 'Ulcer AMR',
    'vaz_2101_broken': 'VAZ-2101 (Quebrado)',
    'vector_a': 'Vector-A',
    'vintorez': 'Vintorez',
    'weapon_box': 'Caixa de Armas',
    'witch_s_punch': 'Soco da Bruxa',
    'wolfsbane_1': 'Wolfsbane-1',
    'zaz_968_broken': 'ZAZ-968 (Quebrado)',
    'zil_130_broken': 'ZIL-130 (Quebrado)',
    'akm_c': 'AKM-C',
    'd_eagle': 'Desert Eagle',
    'nagant_revolver_broken': 'Revolver Nagant (Quebrado)',
    'makarov_handgun_broken': 'Pistola Makarov (Quebrada)',
    'mosin_nagant_rifle_broken': 'Rifle Mosin-Nagant (Quebrado)',
    'broken_car_battery': 'Bateria de Carro Quebrada',
    'car_battery': 'Bateria de Carro',
    'comcon_3_paste': 'Pasta ComCon-3',
    
    # ===== Medicamentos e Quimicos =====
    'acidoemitter': 'Acidoemitter',
    'activated_charcoal': 'Carvao Ativado',
    'antidote': 'Antidoto',
    'antirad': 'Antirad',
    'biotonic': 'Biotonico',
    'broadleaf_plantain': 'Tanchagem',
    'detoxifying_potion': 'Pocao Desintoxicante',
    'energizing_potion': 'Pocao Energizante',
    'eurekognasol_stimulant': 'Estimulante Eurekognasol',
    'acid_gland': 'Glandula Acida',
    'lidiacide_34': 'Lidiacide-34',
    'metocaine': 'Metocaina',
    'painkiller': 'Analgésico',
    'poisoned_flask': 'Frasco Envenenado',
    'protection_potion': 'Pocao de Protecao',
    'sterile_bandage': 'Bandagem Esteril',
    'stimulant': 'Estimulante',
    'sulfuric_acid': 'Acido Sulfurico',
    'chlorcystamine': 'Clorcistamina',
    'vial_of_amine': 'Frasco de Amina',
    
    # ===== Municoes e Explosivos =====
    'crossbow_bolt_poison': 'Virote de Besta (Venenoso)',
    'grenade_launcher_round': 'Granada de Lançador',
    'handmade_rocket': 'Foguete Artesanal',
    'homemade_rocket_launcher': 'Lancador de Foguetes Artesanal',
    'plastic_explosives': 'Explosivos Plasticos',
    'pyrolytic_grenade': 'Granada Pirolitica',
    'revolver_ammo': 'Municao de Revolver',
    'revolver_shell': 'Cartucho de Revolver',
    'training_ammo': 'Municao de Treinamento',
    
    # ===== Armas =====
    'alien_blaster': 'Blaster Alienigena',
    'assault_rifle_parts': 'Pecas de Fuzil de Assalto',
    'berdan_rifle': 'Rifle Berdan',
    'borschevik_flamethrower': 'Lancachamas Borschevik',
    'chemist_crossbow': 'Besta do Quimico',
    'cypress_smg': 'SMG Cypress',
    'flamethrower': 'Lancachamas',
    'flint_knife': 'Faca de Pedra',
    'homemade_pistol': 'Pistola Artesanal',
    'homemade_revolver': 'Revolver Artesanal',
    'homemade_smg': 'SMG Artesanal',
    'hunter_s_rifle': 'Rifle do Cacador',
    'hunting_bow': 'Arco de Caca',
    'jack_o_launcher': 'Lancador Jack O\'',
    'kitchen_knife': 'Faca de Cozinha',
    'multi_shot_rifle': 'Rifle Multi-Tiro',
    'pistol_silent': 'Pistola Silenciosa',
    'pistol_parts': 'Pecas de Pistola',
    'popgun': 'Arma de Brinquedo',
    'revolver_parts': 'Pecas de Revolver',
    'revolving_gun': 'Arma Rotativa',
    'rusted_axe': 'Machado Enferrujado',
    'rusted_crowbar': 'Pe de Cabra Enferrujado',
    'rusted_hacksaw': 'Serra Enferrujada',
    'rusted_needle': 'Agulha Enferrujada',
    'rusted_shovel': 'Pa Enferrujada',
    'single_shot_rifle': 'Rifle de Tiro Unico',
    'shotgun_round': 'Cartucho de Escopeta',
    'sturdy_needle': 'Agulha Resistente',
    'strong_bat': 'Taco Forte',
    'strychnine_gas_revolver': 'Revolver de Gas Estricnina',
    'physicist_crossbow': 'Besta do Fisico',
    'standard_crossbow': 'Besta Padrao',
    'storm_snowball_launcher': 'Lancador de Bolas de Neve Tempestade',
    'handmade_needle': 'Agulha Artesanal',
    'rifle_parts': 'Pecas de Rifle',
    'machine_gun_parts': 'Pecas de Metralhadora',
    'steel_axe': 'Machado de Aco',
    'steel_knife': 'Faca de Aco',
    'titanium_axe': 'Machado de Titanio',
    'titanium_knife': 'Faca de Titanio',
    'nuclear_battery': 'Bateria Nuclear',
    'heavy_machine_gun': 'Metralhadora Pesada',
    'light_machine_gun': 'Metralhadora Leve',
    'rainbow_easter_egg': 'Ovo de Pascoa Arco-Iris',
    'steel_needle': 'Agulha de Aco',
    'steel_shovel': 'Pa de Aco',
    'titanium_shovel': 'Pa de Titanio',
    'titanium_crowbar': 'Pe de Cabra de Titanio',
    'tool_kit': 'Kit de Ferramentas',
    
    # ===== Armaduras =====
    'armored_uniform': 'Uniforme Blindado',
    'armorpiercer': 'Perfurador de Blindagem',
    'bs_4_power_armor': 'Armadura Energetica BS-4',
    'kevlar_vest': 'Colete Kevlar',
    'ghost_suit': 'Traje Fantasma',
    'armor_plate': 'Placa de Blindagem',
    'polar_armor': 'Armadura Polar',
    'tank_armor': 'Armadura de Tanque',
    'tester_armor': 'Armadura de Teste',
    'ghillie_suit': 'Traje de Camuflagem',
    'armorpiercer': 'Perfurador de Blindagem',
    
    # ===== Equipamentos =====
    'chemistry_set': 'Kit de Quimica',
    'glutton_s_bag': 'Bolsa do Gula',
    'invisibility_cloak': 'Manta de Invisibilidade',
    'ermak_backpack': 'Mochila Ermak',
    'refrigerator_backpack': 'Mochila Geladeira',
    'medical_backpack': 'Mochila Medica',
    'tourist_backpack': 'Mochila de Turista',
    'butcher_s_backpack': 'Mochila do Acougueiro',
    
    # ===== Roupas =====
    'cabbage_roll': 'Rolinho de Repolho',
    'handmade_clothes': 'Roupa Artesanal',
    'tattered_clothes': 'Roupa Esfarrapada',
    'normal_clothes': 'Roupa Normal',
    'hunter_s_garb': 'Traje do Cacador',
    'field_uniform': 'Uniforme de Campanha',
    'military_uniform': 'Uniforme Militar',
    'leather_armor': 'Armadura de Couro',
    'master_s_garb': 'Traje do Mestre',
    'smuggler_s_armor': 'Armadura do Contrabandista',
    'prospector_s_armor': 'Armadura do Prospetor',
    'chemical_suit': 'Traje Quimico',
    'demon_mask': 'Mascara de Demonio',
    
    # ===== Ferramentas =====
    'electrodes': 'Eletrodos',
    'bellows': 'Fole',
    'rodkin': 'Rodkin',
    'chimney': 'Chamine',
    'crane': 'Guindaste',
    'oar': 'Remo',
    'welder': 'Soldador',
    'kettlebell': 'Peso Russo',
    'log': 'Tronco',
    'stick': 'Graveto',
    'bowl_of_rice': 'Tigela de Arroz',
    
    # ===== Mascaras de Gas =====
    'comfortable_gas_mask': 'Mascara de Gas Confortavel',
    'gas_mask_filter': 'Filtro de Mascara de Gas',
}

# Apply translations
count = 0
for cat in data['categories']:
    for item in cat['items']:
        item_id = item['id']
        if item_id in translations:
            old_name = item['name']
            item['name'] = translations[item_id]
            count += 1
            print(f'  {item_id}: "{old_name}" -> "{item["name"]}"')

print(f'Total items translated: {count}')

with open('/home/z/my-project/src/data/prices.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print('prices.json saved!')
