#!/usr/bin/env python3
"""
Gerador massivo de dicionário de correção ortográfica para 13 idiomas.
Gera o arquivo spellcheck-dicts.ts com QUICK_FIXES e VOCATIVE_RULES.
"""

import json

def dedup(entries: dict) -> dict:
    """Remove identity mappings e dedupa."""
    return {k: v for k, v in entries.items() if k != v}

def sort_dict(d: dict) -> dict:
    return dict(sorted(d.items()))

# ═══════════════════════════════════════════════════════════
# PORTUGUÊS (pt)
# ═══════════════════════════════════════════════════════════
pt = {
    # ── Acentuação ──
    "voce": "você", "voces": "vocês", "vocez": "você",
    "tambem": "também", "tambe": "também", "tambemm": "também",
    "nao": "não", "naum": "não", "nam": "não", "nah": "não",
    "porem": "porém", "porquem": "por quem",
    "ninguem": "ninguém", "ninguen": "ninguém",
    "alguem": "alguém", "alguen": "alguém",
    "alem": "além", "alemm": "além",
    "ate": "até", "ateh": "até",
    "ja": "já", "jah": "já",
    "so": "só", "soh": "só",
    "pos": "pós", "preh": "pré", "pre": "pré",
    "util": "útil", "utill": "útil", "inutil": "inútil", "inutill": "inútil",
    "facil": "fácil", "facill": "fácil",
    "dificil": "difícil", "dificill": "difícil",
    "possivel": "possível", "possivell": "possível",
    "impossivel": "impossível", "impossivell": "impossível",
    "necessario": "necessário", "necessari": "necessário",
    "obrigado": "obrigado", "obrigada": "obrigada",
    "porke": "porque", "porqe": "porque", "porquie": "porque",
    "muito": "muito", "muito": "muito",
    "mais": "mais", "mas": "mas",
    "voce": "você",
    # ── Erros comuns ──
    "ideo": "idéia", "ideia": "ideia",
    "iniciativa": "iniciativa",
    "beneficio": "benefício", "beneficios": "benefícios",
    "exercicio": "exercício", "exercicios": "exercícios",
    "comercio": "comércio",
    "prejuizo": "prejuízo", "prejuisos": "prejuízos",
    "calcado": "calçado", "calcados": "calçados",
    "cegonha": "cegonha",
    "chapeu": "chapéu", "chapeus": "chapéus",
    "conhecimento": "conhecimento",
    "coracao": "coração", "coracoes": "corações",
    "creanca": "criança", "cricanca": "criança",
    "decisao": "decisão", "decisoes": "decisões",
    "defeito": "defeito",
    "desejo": "desejo",
    "dinheiro": "dinheiro",
    "dono": "dono",
    "educacao": "educação",
    "emocao": "emoção", "emocoes": "emoções",
    "esperanca": "esperança",
    "excecao": "exceção", "excecoes": "exceções",
    "experiencia": "experiência",
    "fabrica": "fábrica",
    "farmacia": "farmácia",
    "forca": "força",
    "funcao": "função", "funcoes": "funções",
    "gratidao": "gratidão",
    "heroi": "herói", "herois": "heróis",
    "historia": "história", "historias": "histórias",
    "igreja": "igreja",
    "ilusao": "ilusão", "ilusoes": "ilusões",
    "impressao": "impressão",
    "informacao": "informação", "informacoes": "informações",
    "iniciativa": "iniciativa",
    "inseguranca": "insegurança",
    "intenção": "intenção", "intencao": "intenção",
    "lembranca": "lembrança",
    "liberdade": "liberdade",
    "miolo": "miolo",
    "moradia": "moradia",
    "mulher": "mulher",
    "necessidade": "necessidade",
    "nobreza": "nobreza",
    "obrigacao": "obrigação",
    "ocasiao": "ocasião", "ocasiao": "ocasião",
    "opiniao": "opinião", "opinioes": "opiniões",
    "orientacao": "orientação",
    "paixao": "paixão",
    "parabens": "parabéns",
    "patrao": "patrão",
    "perfeicao": "perfeição",
    "pergunta": "pergunta",
    "perseguicao": "perseguição",
    "poderiao": "poderiam",
    "preparacao": "preparação",
    "primeiro": "primeiro",
    "privilegio": "privilégio",
    "problema": "problema",
    "procuracao": "procuração",
    "promocao": "promoção",
    "proporcao": "proporção",
    "qualidade": "qualidade",
    "quantidade": "quantidade",
    "questao": "questão", "questoes": "questões",
    "razao": "razão", "razoes": "razões",
    "receita": "receita",
    "reclamacao": "reclamação",
    "recomendacao": "recomendação",
    "reuniao": "reunião", "reunioes": "reuniões",
    "sabedoria": "sabedoria",
    "satisfacao": "satisfação",
    "sensacao": "sensação", "sensacoes": "sensações",
    "situacao": "situação", "situacoes": "situações",
    "solucao": "solução", "solucoes": "soluções",
    "tentacao": "tentação",
    "tradicao": "tradição",
    "unico": "único", "unica": "única",
    "utilidade": "utilidade",
    "vagabundo": "vagabundo",
    "vergonha": "vergonha",
    "viagem": "viagem", "viagens": "viagens",
    "vitoria": "vitória", "vitorias": "vitórias",
    "voluntario": "voluntário",
    "verdade": "verdade",
    # ── Corpo / saúde ──
    "cabeca": "cabeça",
    "braco": "braço", "brazo": "braço",
    "mao": "mão",
    "pe": "pé",
    "coracao": "coração",
    "pulmao": "pulmão",
    "figado": "fígado",
    "estomago": "estômago",
    "infecao": "infecção",
    "virus": "vírus",
    "bacteria": "bactéria",
    "doenca": "doença",
    "antidoto": "antídoto",
    "antibiotico": "antibiótico",
    "anestesico": "anestésico",
    "analgesico": "analgésico",
    # ── Comida / bebida ──
    "feijao": "feijão",
    "pao": "pão", "paes": "pães",
    "macarrao": "macarrão",
    "acucar": "açúcar",
    "oleo": "óleo",
    "cafe": "café",
    "cha": "chá",
    "agua": "água",
    "limao": "limão",
    "maca": "maçã",
    "aviao": "avião",
    "onibus": "ônibus",
    "gas": "gás",
    "lampada": "lâmpada",
    "radio": "rádio",
    "refugio": "refúgio",
    "abacaxi": "abacaxi",
    # ── Construções / lugares ──
    "construcao": "construção",
    "edificio": "edifício",
    "predio": "prédio",
    "tunel": "túnel",
    "piscina": "piscina",
    "aluminio": "alumínio",
    "combustivel": "combustível",
    "caminhao": "caminhão",
    "helicoptero": "helicóptero",
    # ── Verbos comuns ──
    "tiveram": "tiveram", "tver": "tiver",
    "fazer": "fazer", "fazer": "fazer",
    "pode": "pode", "podem": "podem",
    "quer": "quer", "quero": "quero",
    "sabe": "sabe", "saber": "saber",
    "vem": "vem", "vira": "vira",
    "fala": "fala", "falar": "falar",
    "vai": "vai", "vao": "vão",
    "esta": "está", "estao": "estão",
    "tinha": "tinha", "tinham": "tinham",
    "fazia": "fazia", "faziam": "faziam",
    "podia": "podia", "podiam": "podiam",
    "queria": "queria", "queriam": "queriam",
    "sabia": "sabia", "sabiam": "sabiam",
    "vinha": "vinha", "vinham": "vinham",
    "ia": "ia", "iam": "iam",
    "sera": "será", "serao": "serão",
    "tera": "terá", "terao": "terão",
    "fara": "fará", "farao": "farão",
    "poderia": "poderia", "poderiam": "poderiam",
    "gostaria": "gostaria",
    "devia": "devia", "deviam": "deviam",
    # ── Palavras comuns erradas ──
    "txei": "tive", "tbm": "também", "tmb": "também",
    "vc": "você", "vcs": "vocês",
    "pq": "porque", "q": "que", "qq": "qualquer",
    "kd": "cadê", "cd": "cadê",
    "blz": "beleza", "mto": "muito", "mt": "muito",
    "nt": "não", "n": "não",
    "sdd": "saudades", "sdds": "saudades",
    "td": "tudo", "tds": "todos",
    "flw": "falou", "vlw": "valeu",
    "obg": "obrigado", "obgd": "obrigado",
    "aen": "ah é", "ahn": "ah é",
    "isa": "isso", "cisa": "coisa", "cizas": "coisas",
    "bom": "bom", "boa": "boa",
    "bonito": "bonito", "bonita": "bonita",
    "bonito": "bonito",
    "grande": "grande", "grandi": "grande",
    "pequeno": "pequeno", "pequena": "pequena",
    "velho": "velho", "velha": "velha",
    "novo": "novo", "nova": "nova",
    "rapido": "rápido", "rapida": "rápida",
    "lento": "lento", "lenta": "lenta",
    "forte": "forte", "fraco": "fraco",
    "feliz": "feliz", "triste": "triste",
    "bonito": "bonito", "feio": "feio",
    "rico": "rico", "pobre": "pobre",
    "alto": "alto", "baixo": "baixo",
    "longe": "longe", "perto": "perto",
    "quente": "quente", "frio": "frio",
    "grande": "grande", "pequeno": "pequeno",
    "bom": "bom", "mau": "mau",
    "melhor": "melhor", "pior": "pior",
    "sempre": "sempre", "nunca": "nunca",
    "tambem": "também",
    "tudo": "tudo", "nada": "nada",
    "aqui": "aqui", "ali": "ali", "la": "lá", "lah": "lá",
    "agora": "agora", "ja": "já", "jah": "já",
    "hoje": "hoje", "amanha": "amanhã", "amanhã": "amanhã",
    "ontem": "ontem",
    "sempre": "sempre", "nunca": "nunca",
    "muito": "muito", "pouco": "pouco",
    "casa": "casa", "casas": "casas",
    "rua": "rua", "ruas": "ruas",
    "praça": "praça", "praca": "praça",
    "cidade": "cidade", "cidades": "cidades",
    "pais": "país", "paises": "países",
    "mundo": "mundo",
    "terra": "terra",
    "ceu": "céu", "ceus": "céus",
    "sol": "sol", "lua": "lua",
    "estrela": "estrela",
    "chuva": "chuva",
    "vento": "vento",
    "tempo": "tempo",
    "noite": "noite", "dia": "dia",
    "manha": "manhã", "manhã": "manhã",
    "tarde": "tarde",
    "hora": "hora", "horas": "horas",
    "minuto": "minuto", "minutos": "minutos",
    "segundo": "segundo", "segundos": "segundos",
    "semana": "semana", "semanas": "semanas",
    "mes": "mês", "meses": "meses",
    "ano": "ano", "anos": "anos",
    "janeiro": "janeiro", "fevereiro": "fevereiro",
    "marco": "março", "abril": "abril", "maio": "maio",
    "junho": "junho", "julho": "julho", "agosto": "agosto",
    "setembro": "setembro", "outubro": "outubro",
    "novembro": "novembro", "dezembro": "dezembro",
    # ── Números por extenso ──
    "um": "um", "dois": "dois", "tres": "três", "quatro": "quatro",
    "cinco": "cinco", "seis": "seis", "sete": "sete", "oito": "oito",
    "nove": "nove", "dez": "dez", "cem": "cem", "mil": "mil",
    "primeiro": "primeiro", "segundo": "segundo", "terceiro": "terceiro",
    "quarto": "quarto", "quinto": "quinto",
    # ── Família ──
    "mae": "mãe", "pai": "pai",
    "irmao": "irmão", "irma": "irmã",
    "filho": "filho", "filha": "filha",
    "avo": "avô", "avo": "avó",
    "tio": "tio", "tia": "tia",
    "primo": "primo", "prima": "prima",
    "sobrinho": "sobrinho", "sobrinha": "sobrinha",
    "marido": "marido", "esposa": "esposa",
    "filhos": "filhos", "filhas": "filhas",
    "irmaos": "irmãos", "irmas": "irmãs",
    # ── Pronomes / preposições erradas ──
    "nos": "nós", "vos": "vós",
    "senao": "senão",
    "tras": "trás",
    "num": "num",  # em+um
    "numa": "numa",  # em+uma
    "nuns": "nuns", "numas": "numas",
    "neste": "neste", "nesta": "nesta",
    "nesse": "nesse", "nessa": "nessa",
    "naquele": "naquele", "naquela": "naquela",
    "daquele": "daquele", "daquela": "daquela",
    "daqui": "daqui", "dali": "dali",
    "porque": "porque",
    "porquanto": "porquanto",
    # ── Jogos / sobrevivência ──
    "zumbi": "zumbi", "zumbis": "zumbis",
    "sobrevivente": "sobrevivente",
    "sobrevivencia": "sobrevivência",
    "arma": "arma", "armas": "armas",
    "municao": "munição", "municao": "munição",
    "provisao": "provisão",
    "abrigo": "abrigo",
    "barraca": "barraca",
    "acampamento": "acampamento",
    "fogueira": "fogueira",
    "lanterna": "lanterna",
    "bateria": "bateria",
    "gerador": "gerador",
    "remedio": "remédio", "remedios": "remédios",
    "curativo": "curativo",
    "bandagem": "bandagem",
    "comida": "comida",
    "bebida": "bebida",
    "agua": "água",
    "fome": "fome",
    "sede": "sede",
    "energia": "energia",
    "vida": "vida",
    "morte": "morte",
    "perigo": "perigo",
    "seguranca": "segurança",
    "protecao": "proteção",
    "defesa": "defesa",
    "ataque": "ataque",
    "inimigo": "inimigo",
    "aliado": "aliado",
    "grupo": "grupo",
    "equipe": "equipe",
    "missao": "missão",
    "objetivo": "objetivo",
    "estrategia": "estratégia",
    "recurso": "recurso", "recursos": "recursos",
    "material": "material", "materiais": "materiais",
    "ferramenta": "ferramenta", "ferramentas": "ferramentas",
    "madeira": "madeira",
    "pedra": "pedra", "pedras": "pedras",
    "metal": "metal",
    "ferro": "ferro",
    "aco": "aço",
    "ouro": "ouro",
    "prata": "prata",
    "cobre": "cobre",
    "tecido": "tecido",
    "corda": "corda",
    "cola": "cola",
    "papel": "papel",
    "livro": "livro",
    "mapa": "mapa",
    "bussola": "bússola",
    "isqueiro": "isqueiro",
    "fosforo": "fósforo",
    "vela": "vela",
    "tocha": "tocha",
    # ── Conectivos ──
    "porem": "porém",
    "contudo": "contudo",
    "entretanto": "entretanto",
    "portanto": "portanto",
    "logo": "logo",
    "pois": "pois",
    "inclusive": "inclusive",
    "ademais": "ademais",
    "alem": "além",
    "assim": "assim",
    "contanto": "contanto",
    "conforme": "conforme",
    "conquanto": "conquanto",
    "embora": "embora",
    "enquanto": "enquanto",
    "mesmo": "mesmo",
    "portanto": "portanto",
    "poranto": "poranto",
    "porisso": "por isso",
    "porisso": "por isso",
    "ja": "já",
    "quando": "quando",
    "sempre": "sempre",
    "geralmente": "geralmente",
    "normalmente": "normalmente",
    "frequentemente": "frequentemente",
    "raramente": "raramente",
    "ocasionalmente": "ocasionalmente",
    "provavelmente": "provavelmente",
    "certamente": "certamente",
    "realmente": "realmente",
    "obviamente": "obviamente",
    "exatamente": "exatamente",
    "praticamente": "praticamente",
    "basicamente": "basicamente",
    "simplesmente": "simplesmente",
    "naturalmente": "naturalmente",
    "infelizmente": "infelizmente",
    "felizmente": "felizmente",
    # ── Erros de digitação comuns ──
    "thau": "tão", "tao": "tão", "tão": "tão",
    "vem": "vem", "vemsera": "vém ser",
    "cabe": "cabe",
    "falta": "falta",
    " gente": "gente",
    "coisa": "coisa", "coisas": "coisas",
    "tipo": "tipo", "tipos": "tipos",
    "modo": "modo",
    "forma": "forma",
    "lugar": "lugar",
    "parte": "parte",
    "ponto": "ponto",
    "caso": "caso",
    "vez": "vez",
    "motivo": "motivo",
    "causa": "causa",
    "razao": "razão",
    "problema": "problema",
    "situacao": "situação",
    "solucao": "solução",
    "resposta": "resposta",
    "pergunta": "pergunta",
    "dúvida": "dúvida", "duvida": "dúvida",
    "ajuda": "ajuda",
    "suporte": "suporte",
    "favor": "favor",
    "obrigado": "obrigado",
    "porfavor": "por favor",
    "desculpa": "desculpa",
    "desculpe": "desculpe",
    "porfavor": "por favor",
    "com certeza": "com certeza",
    "talvez": "talvez",
    "quase": "quase",
    "apenas": "apenas",
    "também": "também",
    "menos": "menos",
    "cada": "cada",
    "todo": "todo", "toda": "toda", "todos": "todos", "todas": "todas",
    "outro": "outro", "outra": "outra",
    "muito": "muito", "muita": "muita", "muitos": "muitos", "muitas": "muitas",
    "pouco": "pouco", "pouca": "pouca", "poucos": "poucos", "poucas": "poucas",
    # ── Mais erros de acentuação ──
    "saude": "saúde",
    "gratidao": "gratidão",
    "compaixao": "compaixão",
    "perfeicao": "perfeição",
    "paixao": "paixão",
    "nação": "nação", "nacao": "nação",
    "estação": "estação", "estacao": "estação",
    "operação": "operação", "operacao": "operação",
    "ação": "ação", "acao": "ação",
    "reclamação": "reclamação", "reclamacao": "reclamação",
    "administração": "administração", "administracao": "administração",
    "comunicação": "comunicação", "comunicacao": "comunicação",
    "organização": "organização", "organizacao": "organização",
    "situação": "situação",
    "informação": "informação",
    "educação": "educação",
    "população": "população", "populacao": "população",
    "avaliação": "avaliação", "avaliacao": "avaliação",
    "preparação": "preparação",
    "programação": "programação", "programacao": "programação",
    "confirmação": "confirmação", "confirmacao": "confirmação",
    "versão": "versão", "versao": "versão",
    "tensão": "tensão", "tensao": "tensão",
    "extensão": "extensão", "extensao": "extensão",
    "intenção": "intenção",
    "atenção": "atenção", "atencao": "atenção",
    "prevenção": "prevenção", "prevencao": "prevenção",
    "proteção": "proteção", "protecao": "proteção",
    "direção": "direção", "direcao": "direção",
    "correção": "correção", "correcao": "correção",
    "conexão": "conexão", "conexao": "conexão",
    "seleção": "seleção", "selecao": "seleção",
    "coleção": "coleção", "colecao": "coleção",
    "reflexão": "reflexão", "reflexao": "reflexão",
    "destruição": "destruição", "destruicao": "destruição",
    "construção": "construção",
    "produção": "produção", "producao": "produção",
    "redução": "redução", "reducao": "redução",
    "adição": "adição", "adicao": "adição",
    "subtração": "subtração", "subtracao": "subtração",
    "multiplicação": "multiplicação", "multiplicacao": "multiplicação",
    "divisão": "divisão", "divisao": "divisão",
    "explosão": "explosão", "explosao": "explosão",
    "invasão": "invasão", "invasao": "invasão",
    "decisão": "decisão",
    "visão": "visão", "visao": "visão",
    "missão": "missão", "missao": "missão",
    "paixão": "paixão",
    "ilusão": "ilusão",
    "conclusão": "conclusão", "conclusao": "conclusão",
    "clusula": "cláusula",
    "condição": "condição", "condicao": "condição",
    "posição": "posição", "posicao": "posição",
    "composição": "composição", "composicao": "composição",
    "exposição": "exposição", "exposicao": "exposição",
    "impressão": "impressão",
    "expressão": "expressão", "expressao": "expressão",
    "sessão": "sessão", "sessao": "sessão",
    "cessão": "cessão", "cessao": "cessão",
    "progressão": "progressão", "progressao": "progressão",
    "sessão": "sessão",
    "profissão": "profissão", "profissao": "profissão",
    "permissão": "permissão", "permissao": "permissão",
    "admissão": "admissão", "admissao": "admissão",
    "transmissão": "transmissão", "transmissao": "transmissão",
    "comissão": "comissão", "comissao": "comissão",
    "dimensão": "dimensão", "dimensao": "dimensão",
    "expansão": "expansão", "expansao": "expansão",
    "pretensão": "pretensão", "pretensao": "pretensão",
    "dispensão": "dispensão", "dispensao": "dispensão",
    "potenciação": "potenciação",
    "relação": "relação", "relacao": "relação",
    "nação": "nação",
    "estação": "estação",
    "senhoria": "senhoria",
    "serviço": "serviço", "servico": "serviço",
    "sacrifício": "sacrifício", "sacrificio": "sacrifício",
    "benefício": "benefício",
    "suplício": "suplício", "suplicio": "suplício",
    "exercício": "exercício",
    "prejuízo": "prejuízo",
    "gênero": "gênero", "genero": "gênero",
    "interesse": "interesse",
    "experiência": "experiência",
    "consciência": "consciência", "consciencia": "consciência",
    "presença": "presença", "presenca": "presença",
    "ausência": "ausência", "ausencia": "ausência",
    "essência": "essência", "essencia": "essência",
    "inocência": "inocência", "inocencia": "inocência",
    "violência": "violência", "violencia": "violência",
    "silêncio": "silêncio", "silencio": "silêncio",
    "necessidade": "necessidade",
    "entidade": "entidade",
    "identidade": "identidade",
    "diversidade": "diversidade",
    "universidade": "universidade",
    "cidade": "cidade",
    "velocidade": "velocidade",
    "capacidade": "capacidade",
    "possibilidade": "possibilidade",
    "probabilidade": "probabilidade",
    "responsabilidade": "responsabilidade",
    "oportunidade": "oportunidade",
    "autoridade": "autoridade",
    "comunidade": "comunidade",
    "sociedade": "sociedade",
    "atividade": "atividade",
    "facilidade": "facilidade",
    "dificuldade": "dificuldade",
    "verdade": "verdade",
    "liberdade": "liberdade",
    "igualdade": "igualdade",
    "franqueza": "franqueza",
    "riqueza": "riqueza",
    "pobreza": "pobreza",
    "beleza": "beleza",
    "tristeza": "tristeza",
    "paz": "paz",
    "guerra": "guerra",
    "amor": "amor",
    "ódio": "ódio", "odio": "ódio",
    "medo": "medo",
    "coragem": "coragem",
    "esperança": "esperança", "esperanca": "esperança",
    "fé": "fé", "fe": "fé",
    "esperança": "esperança",
    "caridade": "caridade",
    "justiça": "justiça", "justica": "justiça",
    "lealdade": "lealdade",
    "honestidade": "honestidade",
    "veracidade": "veracidade",
    "sabedoria": "sabedoria",
    "tolerância": "tolerância", "tolerancia": "tolerância",
    "respeito": "respeito",
    "educação": "educação",
    "cultura": "cultura",
    "ciência": "ciência", "ciencia": "ciência",
    "tecnologia": "tecnologia",
    "natureza": "natureza",
    "meio": "meio",
    "ambiente": "ambiente",
    "ecologia": "ecologia",
    "poluição": "poluição", "poluicao": "poluição",
    "contaminação": "contaminação", "contaminacao": "contaminação",
    "energia": "energia",
    "reciclagem": "reciclagem",
    "sustentável": "sustentável", "sustentavel": "sustentável",
    "desenvolvimento": "desenvolvimento",
    "crescimento": "crescimento",
    "economia": "economia",
    "política": "política", "politica": "política",
    "governo": "governo",
    "democracia": "democracia",
    "república": "república", "republica": "república",
    "presidente": "presidente",
    "ministro": "ministro",
    "parlamento": "parlamento",
    "senado": "senado",
    "eleição": "eleição", "eleicao": "eleição",
    "voto": "voto",
    "partido": "partido",
    "campanha": "campanha",
    "manifestação": "manifestação", "manifestacao": "manifestação",
    "revolução": "revolução", "revolucao": "revolução",
    "independência": "independência", "independencia": "independência",
    "liberdade": "liberdade",
    "constituição": "constituição", "constituicao": "constituição",
    "lei": "lei",
    "direito": "direito",
    "dever": "dever",
    "obrigação": "obrigação",
    "contrato": "contrato",
    "acordo": "acordo",
    "tratado": "tratado",
    "convenção": "convenção", "convencao": "convenção",
    "declaração": "declaração", "declaracao": "declaração",
    "regulamento": "regulamento",
    "norma": "norma",
    "regra": "regra",
    "proibição": "proibição", "proibicao": "proibição",
    "multa": "multa",
    "pena": "pena",
    "punição": "punição", "punicao": "punição",
    "julgamento": "julgamento",
    "sentença": "sentença", "sentenca": "sentença",
    "tribunal": "tribunal",
    "juiz": "juiz",
    "advogado": "advogado",
    "promotor": "promotor",
    "delegado": "delegado",
    "policial": "policial",
    "detetive": "detetive",
    "investigação": "investigação", "investigacao": "investigação",
    "crime": "crime",
    "assalto": "assalto",
    "roubo": "roubo",
    "furto": "furto",
    "homicídio": "homicídio", "homicidio": "homicídio",
    "sequestro": "sequestro",
    "fraude": "fraude",
    "corrupção": "corrupção", "corrupcao": "corrupção",
    "escândalo": "escândalo", "escandalo": "escândalo",
    "denúncia": "denúncia", "denuncia": "denúncia",
    "queixa": "queixa",
    "reclamação": "reclamação",
    "protesto": "protesto",
    "greve": "greve",
    "reivindicação": "reivindicação", "reivindicacao": "reivindicação",
}

# ═══════════════════════════════════════════════════════════
# ENGLISH (en)
# ═══════════════════════════════════════════════════════════
en = {
    # ── Common typos ──
    "teh": "the", "hte": "the", "th": "the", "tha": "the",
    "adn": "and", "amd": "and", "abd": "and", "nad": "and",
    "taht": "that", "thta": "that", "htat": "that", "thar": "that",
    "fro": "for", "ofr": "for", "fr": "for", "fora": "for",
    "ot": "to", "t": "to",
    "wiht": "with", "wit": "with", "wih": "with", "whti": "with",
    "oyu": "you", "yuo": "you", "yo": "you", "yu": "you", "ouy": "you",
    "si": "is", "i": "I",
    "ti": "it", "ut": "it", "ith": "it",
    "ni": "in", "im": "in", "ib": "in",
    "htat": "that",
    "this": "this", "thsi": "this", "thi": "this", "tihs": "this",
    "hvae": "have", "ahve": "have", "hav": "have", "hsve": "have", "hvea": "have",
    "has": "has", "had": "had", "hda": "had", "adh": "had",
    "was": "was", "wsa": "was", "wsa": "was",
    "were": "were", "wer": "were", "weer": "were", "wree": "were",
    "be": "be", "been": "been", "beeen": "been", "ben": "been",
    "being": "being", "beign": "being", "beng": "being",
    "am": "am", "are": "are", "rare": "are", "aer": "are",
    "do": "do", "od": "do", "does": "does", "dose": "does", "doed": "does",
    "did": "did", "ddi": "did", "idd": "did",
    "will": "will", "wil": "will", "wll": "will", "wlil": "will",
    "would": "would", "woudl": "would", "wuld": "would", "woud": "would",
    "could": "could", "coudl": "could", "culd": "could", "coud": "could", "colud": "could",
    "should": "should", "shoudl": "should", "shuld": "should", "shoud": "should",
    "can": "can", "cna": "can", "acn": "can",
    "may": "may", "might": "might", "migth": "might", "mihgt": "might",
    "must": "must", "msut": "must", "muts": "must",
    "shall": "shall", "shlal": "shall", "hsall": "shall",
    "not": "not", "nto": "not", "no": "no", "not": "not",
    "but": "but", "btu": "but", "bu": "but", "ubt": "but",
    "or": "or", "ro": "or",
    "if": "if", "fi": "if",
    "then": "then", "hten": "then", "thne": "then", "tehn": "then",
    "than": "than", "htan": "than", "thna": "than", "tahn": "than",
    "so": "so", "os": "so",
    "as": "as", "sa": "as",
    "at": "at", "ta": "at",
    "by": "by", "yb": "by",
    "from": "from", "form": "from", "frm": "from", "rfom": "from",
    "up": "up", "pu": "up",
    "down": "down", "donw": "down", "dwon": "down", "odwn": "down",
    "out": "out", "otu": "out", "ou": "out",
    "off": "off", "fof": "off", "off": "off",
    "over": "over", "ovre": "over", "ove": "over", "oever": "over",
    "under": "under", "unedr": "under", "undre": "under", "udner": "under",
    "again": "again", "agian": "again", "agani": "again", "agin": "again",
    "further": "further", "futher": "further", "futrher": "further",
    "once": "once", "noce": "once", "ocne": "once",
    "here": "here", "hre": "here",
    "there": "there", "thre": "there", "ther": "there", "thier": "their",
    "when": "when", "whne": "when", "wen": "when", "wehn": "when",
    "where": "where", "whre": "where", "were": "where", "whree": "where",
    "why": "why", "wyh": "why", "hyw": "why",
    "how": "how", "ohw": "how", "ho": "how",
    "all": "all", "al": "all", "lal": "all",
    "each": "each", "eac": "each", "ech": "each",
    "every": "every", "evry": "every", "evrey": "every", "eveyr": "every",
    "both": "both", "boht": "both", "btoh": "both",
    "few": "few",
    "more": "more", "mroe": "more", "moer": "more", "omre": "more",
    "most": "most", "mos": "most", "omst": "most", "mot": "most",
    "other": "other", "othre": "other", "ohter": "other", "othr": "other",
    "some": "some", "soem": "some", "smoe": "some", "osme": "some",
    "such": "such", "suhc": "such", "scuh": "such",
    "any": "any", "ayn": "any", "nya": "any", "nay": "any",
    "only": "only", "onyl": "only", "oly": "only", "onyl": "only",
    "same": "same", "smae": "same", "saem": "same",
    "also": "also", "aslo": "also", "alos": "also",
    "just": "just", "jsut": "just", "juts": "just", "jus": "just",
    "very": "very", "veyr": "very", "vrey": "very", "vrye": "very",
    "often": "often", "oten": "often", "oftne": "often",
    "now": "now", "nw": "now", "no": "now",
    "well": "well", "wlle": "well", "wel": "well", "wlel": "well",
    "back": "back", "bakc": "back", "bck": "back", "bac": "back",
    "even": "even", "evne": "even", "eve": "even",
    "still": "still", "stlil": "still", "stli": "still",
    "already": "already", "alreday": "already", "alrady": "already",
    "always": "always", "awlays": "always", "alawys": "always", "alwyas": "always",
    "never": "never", "nevre": "never", "nver": "never", "neevr": "never",
    "about": "about", "abuot": "about", "abot": "about", "bout": "about", "abotu": "about",
    "after": "after", "aftre": "after", "afetr": "after", "afte": "after",
    "before": "before", "befor": "before", "befroe": "before", "befoer": "before",
    "between": "between", "bewteen": "between", "betwen": "between", "betwee": "between",
    "through": "through", "throuhg": "through", "thorugh": "through", "throug": "through",
    "during": "during", "durign": "during", "duirng": "during",
    "while": "while", "whiel": "while", "whle": "while",
    "until": "until", "untl": "until", "util": "until", "untli": "until",
    "since": "since", "sice": "since", "sinse": "since",
    "because": "because", "becuase": "because", "beacuse": "because", "becaus": "because", "beacsue": "because",
    "however": "however", "hoever": "however", "howver": "however", "howeve": "however",
    "although": "although", "althogh": "although", "althouh": "although",
    "though": "though", "thogh": "though", "thouh": "though", "thoug": "though",
    "either": "either", "eithe": "either", "eithr": "either", "eihter": "either",
    "neither": "neither", "niether": "neither", "nehtier": "neither", "neithe": "neither",
    "whether": "whether", "wheter": "whether", "whehter": "whether", "whther": "whether",
    "these": "these", "thsee": "these", "thees": "these", "tehse": "these",
    "those": "those", "thsoe": "those", "thoes": "those", "tohse": "those",
    "which": "which", "whcih": "which", "whihc": "which", "hwich": "which",
    "what": "what", "waht": "what", "whta": "what", "hwat": "what",
    "who": "who", "hwo": "who", "woh": "who",
    "whom": "whom", "whmo": "whom", "whm": "whom",
    "whose": "whose", "whoes": "whose", "whos": "whose",
    "many": "many", "amny": "many", "mnay": "many", "manay": "many",
    "much": "much", "mcuh": "much", "muc": "much", "muhc": "much",
    "own": "own", "won": "own", "wno": "own",

    # ── Contractions ──
    "theyre": "they're", "your": "your", "yuor": "your", "yoru": "your",
    "youre": "you're", "their": "their", "thier": "their", "tehir": "their",
    "dont": "don't", "doesnt": "doesn't", "didnt": "didn't",
    "wont": "won't", "cant": "can't", "shouldnt": "shouldn't",
    "wouldnt": "wouldn't", "couldnt": "couldn't",
    "isnt": "isn't", "arent": "aren't", "wasnt": "wasn't",
    "werent": "weren't", "hasnt": "hasn't", "havent": "haven't",
    "hadnt": "hadn't", "im": "I'm", "ive": "I've",
    "youve": "you've", "theyve": "they've", "weve": "we've",
    "ill": "I'll", "youd": "you'd", "hed": "he'd",
    "shed": "she'd", "wed": "we'd", "theyd": "they'd",
    "lets": "let's", "thats": "that's", "whos": "who's", "whats": "what's",
    "hes": "he's", "shes": "she's", "its": "its",

    # ── Common vocabulary misspellings ──
    "realy": "really", "realyy": "really",
    "beleive": "believe", "belive": "believe",
    "recieve": "receive", "receve": "receive", "recevie": "receive",
    "acheive": "achieve", "achive": "achieve",
    "occured": "occurred", "ocurred": "occurred", "occurrd": "occurred",
    "happend": "happened",
    "begining": "beginning",
    "definately": "definitely", "definatly": "definitely", "definitley": "definitely",
    "seperate": "separate", "seperat": "separate",
    "occassion": "occasion",
    "accomodate": "accommodate", "acommodate": "accommodate",
    "accomodation": "accommodation", "acomodation": "accommodation",
    "occurrence": "occurrence", "occurrance": "occurrence",
    "adress": "address", "addres": "address",
    "accidentaly": "accidentally", "accidently": "accidentally",
    "accomodate": "accommodate",
    "acheive": "achieve",
    "acquire": "acquire", "aquire": "acquire",
    "a lot": "a lot", "alot": "a lot",
    "arguement": "argument",
    "basicly": "basically",
    "beautifull": "beautiful", "beautful": "beautiful",
    "becuase": "because",
    "behaviour": "behavior", "behavoir": "behavior",
    "belive": "believe",
    "benifit": "benefit",
    "buisness": "business", "busness": "business",
    "calender": "calendar",
    "carribean": "caribbean",
    "catagory": "category",
    "cemetery": "cemetery", "cemetary": "cemetery",
    "changable": "changeable",
    "collegue": "colleague",
    "comming": "coming",
    "commitee": "committee",
    "comparision": "comparison",
    "completly": "completely",
    "concious": "conscious",
    "curiousity": "curiosity",
    "database": "database",
    "definetly": "definitely",
    "develope": "develop", "developement": "development",
    "dilemna": "dilemma",
    "dissapoint": "disappoint", "dissappoint": "disappoint",
    "dissappear": "disappear",
    "ecstacy": "ecstasy",
    "embarras": "embarrass", "embarass": "embarrass",
    "enviroment": "environment", "environmant": "environment",
    "equiptment": "equipment", "equipement": "equipment",
    "existance": "existence",
    "expirience": "experience", "experiance": "experience",
    "explaination": "explanation",
    "facinate": "fascinate",
    "February": "February", "Febuary": "February",
    "firey": "fiery",
    "florescent": "fluorescent",
    "foriegn": "foreign",
    "fourty": "forty",
    "freind": "friend", "freind": "friend",
    "fulfil": "fulfill",
    "gaurd": "guard",
    "goverment": "government", "goverment": "government",
    "gratefull": "grateful", "greatful": "grateful",
    "garantee": "guarantee", "garantee": "guarantee",
    "heighth": "height",
    "hierachy": "hierarchy", "heirarchy": "hierarchy",
    "honest": "honest", "honnest": "honest",
    "humour": "humor", "humour": "humor",
    "idiosyncracy": "idiosyncrasy",
    "immediatly": "immediately",
    "importent": "important",
    "independant": "independent",
    "innoculate": "inoculate",
    "inteligence": "intelligence",
    "interst": "interest", "intrest": "interest",
    "irresistable": "irresistible",
    "jewlery": "jewelry", "jewellry": "jewelry",
    "judgement": "judgment",
    "kernal": "kernel",
    "knowlege": "knowledge", "knwoledge": "knowledge",
    "labratory": "laboratory",
    "language": "language", "langauge": "language",
    "layed": "laid",
    "lesure": "leisure",
    "libary": "library", "liberry": "library",
    "liccence": "license", "lisence": "license",
    "lightening": "lightning", "lighting": "lightning",
    "maintainance": "maintenance", "maintnance": "maintenance",
    "manuever": "maneuver", "manouver": "maneuver",
    "medival": "medieval",
    "memento": "memento", "momento": "memento",
    "millenium": "millennium", "milennium": "millennium",
    "minature": "miniature",
    "mischievious": "mischievous", "mischevious": "mischievous",
    "mispell": "misspell", "misspel": "misspell",
    "naturaly": "naturally",
    "neccessary": "necessary", "necesary": "necessary", "neccesary": "necessary",
    "neice": "niece",
    "niether": "neither",
    "noticable": "noticeable",
    "occurence": "occurrence",
    "offically": "officially",
    "oportunity": "opportunity",
    "oppurtunity": "opportunity",
    "optimisim": "optimism",
    "outragous": "outrageous",
    "paralel": "parallel",
    "pasttime": "pastime",
    "persistant": "persistent",
    "pharoah": "pharaoh",
    "playwrite": "playwright",
    "posession": "possession", "posession": "possession",
    "potatos": "potatoes",
    "practicle": "practical",
    "preceed": "precede",
    "priviledge": "privilege", "privelage": "privilege",
    "probly": "probably", "probabbly": "probably",
    "procede": "proceed",
    "pronounciation": "pronunciation",
    "publically": "publicly",
    "questionaire": "questionnaire",
    "readible": "readable",
    "reccomend": "recommend",
    "reccommend": "recommend",
    "refered": "referred", "reffered": "referred",
    "referance": "reference",
    "religous": "religious",
    "rember": "remember", "rembere": "remember",
    "repear": "repair", "repare": "repair",
    "repetion": "repetition",
    "restaraunt": "restaurant", "resturant": "restaurant",
    "recieve": "receive",
    "rythm": "rhythm",
    "sacrafice": "sacrifice",
    "sandwhich": "sandwich",
    "sargent": "sergeant",
    "scisors": "scissors", "scisors": "scissors",
    "secretery": "secretary",
    "segment": "segment",
    "seperate": "separate",
    "sieze": "seize",
    "sentance": "sentence",
    "sholder": "shoulder",
    "speach": "speech",
    "succesful": "successful", "successfull": "successful",
    "supercede": "supersede",
    "suprise": "surprise", "surprize": "surprise",
    "suspence": "suspense",
    "symathy": "sympathy",
    "tommorow": "tomorrow", "tomorow": "tomorrow",
    "tommorrow": "tomorrow",
    "tonite": "tonight",
    "truley": "truly", "truely": "truly",
    "tyrany": "tyranny",
    "undoubtably": "undoubtedly",
    "unfortunatly": "unfortunately",
    "unnecesary": "unnecessary", "unneccesary": "unnecessary",
    "unusal": "unusual",
    "upholstry": "upholstery",
    "usally": "usually", "usualy": "usually",
    "vaccum": "vacuum",
    "vegatable": "vegetable", "vegitable": "vegetable",
    "visious": "vicious",
    "wierd": "weird", "wiered": "weird",
    "writting": "writing",
    "yatch": "yacht",
    "yearly": "yearly",
    "your": "your", "you're": "you're",
    # ── Common word pairs ──
    "alright": "all right",
    "cant": "can't",
    "doesnt": "doesn't",
    "dont": "don't",
    "didnt": "didn't",
    "shouldnt": "shouldn't",
    "wouldnt": "wouldn't",
    "couldnt": "couldn't",
    "isnt": "isn't",
    "arent": "aren't",
    "wasnt": "wasn't",
    "werent": "weren't",
    "hasnt": "hasn't",
    "havent": "haven't",
    "hadnt": "hadn't",
    "wont": "won't",
    "mustnt": "mustn't",
    "neednt": "needn't",
    "shant": "shan't",
    "mightnt": "mightn't",
    "neednt": "needn't",
    # ── Grammar / common errors ──
    "irregardless": "regardless",
    "could of": "could have", "should of": "should have", "would of": "would have",
    "supposably": "supposedly",
    "expresso": "espresso",
    "nother": "another",
    "highjack": "hijack",
    "noone": "no one",
    "setup": "setup", "set up": "set up",
    "everytime": "every time",
    "alright": "all right",
    "infact": "in fact",
    "inspite": "in spite",
    "alot": "a lot",
    "aswell": "as well",
    "infact": "in fact",
    "mean while": "meanwhile",
    "some thing": "something",
    "any thing": "anything",
    "no body": "nobody",
    "every body": "everybody",
    "with out": "without",
    "them selves": "themselves",
    "its": "its", "it's": "it's",
    "lets": "let's",
    # ── More vocabulary ──
    "absoluteley": "absolutely",
    "absolutly": "absolutely",
    "accidentaly": "accidentally",
    "acomodate": "accommodate",
    "acheive": "achieve",
    "acknowlege": "acknowledge",
    "aquire": "acquire",
    "arguement": "argument",
    "assasinate": "assassinate",
    "apropriate": "appropriate",
    "artic": "arctic",
    "assistant": "assistant", "asistant": "assistant",
    "awfull": "awful",
    "baloon": "balloon",
    "barbecue": "barbecue", "barbeque": "barbecue",
    "basicaly": "basically",
    "beautifuly": "beautifully",
    "believe": "believe",
    "biscut": "biscuit",
    "boundry": "boundary",
    "buisness": "business",
    "burgler": "burglar",
    "calender": "calendar",
    "carisma": "charisma",
    "catagory": "category",
    "cemetary": "cemetery",
    "challange": "challenge",
    "charactor": "character",
    "cheif": "chief",
    "choclate": "chocolate",
    "circular": "circular", "circulr": "circular",
    "colledge": "college",
    "comission": "commission",
    "comitment": "commitment",
    "commitee": "committee",
    "comparision": "comparison",
    "competeive": "competitive",
    "completly": "completely",
    "comply": "comply", "complyed": "complied",
    "concious": "conscious",
    "congradulate": "congratulate",
    "consciencious": "conscientious",
    "conscent": "consent",
    "consecutive": "consecutive", "consecuitive": "consecutive",
    "contribute": "contribute", "contribute": "contribute",
    "controversy": "controversy", "contraversy": "controversy",
    "convertable": "convertible",
    "cooly": "coolly",
    "corection": "correction",
    "corresspondence": "correspondence",
    "crucial": "crucial", "cruicial": "crucial",
    "curosity": "curiosity",
    "deadly": "deadly", "deadley": "deadly",
    "decaffinated": "decaffeinated",
    "decieve": "deceive",
    "definetely": "definitely",
    "deparate": "desperate",
    "desparate": "desperate",
    ```: ```,
    "diaster": "disaster",
    "dilemna": "dilemma",
    "dissapoint": "disappoint",
    "divise": "divise",
    "documant": "document",
    "doesnt": "doesn't",
    "dominent": "dominant",
    "drunkenness": "drunkenness",
    "dumbell": "dumbbell",
    "eccentric": "eccentric", "ecccentric": "eccentric",
    "efficent": "efficient",
    "elaborate": "elaborate", "elaberate": "elaborate",
    "eleventy": "eleventy",
    "embarass": "embarrass",
    "eminent": "eminent", "iminent": "imminent",
    "encourage": "encourage", "encourgae": "encourage",
    "enormity": "enormity", "enormosity": "enormity",
    "enthusiatic": "enthusiastic",
    "envelop": "envelop", "envelope": "envelope",
    "epitomy": "epitome",
    "equiptment": "equipment",
    "essense": "essence",
    "exagerrate": "exaggerate",
    "excellant": "excellent",
    "excercise": "exercise",
    "excellence": "excellence", "excellance": "excellence",
    "exept": "except",
    "expirience": "experience",
    "expresion": "expression",
    "extacy": "ecstasy",
    "facinate": "fascinate",
    "fallacy": "fallacy", "fallasy": "fallacy",
    "familar": "familiar",
    "fasinate": "fascinate",
    "fatigue": "fatigue", "fatique": "fatigue",
    "favorite": "favorite", "favourite": "favorite",
    "february": "February",
    "fededral": "federal",
    ```: ```,
    "figgure": "figure",
    "flourescent": "fluorescent",
    "foilage": "foliage",
    "footloose": "footloose",
    "foriegn": "foreign",
    "forword": "forward",
    ```: ```,
    "fourty": "forty",
    ```: ```,
    "freind": "friend",
    "fulfil": "fulfill",
    "further": "further",
    "goverment": "government",
    "gaurd": "guard",
    "grammer": "grammar",
    "granduer": "grandeur",
    "gratefull": "grateful",
    "greatful": "grateful",
    ```: ```,
    "guarentee": "guarantee",
    "guidence": "guidance",
    "halmark": "hallmark",
    "handfull": "handful",
    "harrass": "harass",
    "harasment": "harassment",
    "heighth": "height",
    "heros": "heroes",
    "higest": "highest",
    "honest": "honest",
    "hopful": "hopeful",
    "humourous": "humorous",
    "hygeine": "hygiene",
    "hyppocrite": "hypocrite",
    "idear": "idea",
    "ignorence": "ignorance",
    ```: ```,
    "imaginery": "imaginary",
    ```: ```,
    "immediatly": "immediately",
    "implicit": "implicit", "implict": "implicit",
    "importent": "important",
    "independant": "independent",
    "indispensible": "indispensable",
    "inevitable": "inevitable", "inevitible": "inevitable",
    ```: ```,
    "innoculate": "inoculate",
    "insistant": "insistent",
    "insurence": "insurance",
    "intellegent": "intelligent",
    ```: ```,
    ```: ```,
    "interst": "interest",
    "intolorance": "intolerance",
    ```: ```,
    ```: ```,
    ```: ```,
    ```: ```,
    ```: ```,
    ```: ```,
    ```: ```,
    "judgement": "judgment",
    "kernal": "kernel",
    ```: ```,
    "knowlege": "knowledge",
    "labratory": "laboratory",
    ```: ```,
    "langauge": "language",
    "layed": "laid",
    ```: ```,
    "ledgend": "legend",
    "legitamate": "legitimate",
    "libary": "library",
    "licsence": "license",
    ```: ```,
    "lieing": "lying",
    "lightening": "lightning",
    "liscense": "license",
    "litterature": "literature",
    "loosly": "loosely",
    "lose": "lose",
    "lovely": "lovely",
    "luxery": "luxury",
    "maintainance": "maintenance",
    "managment": "management",
    ```: ```,
    "manuever": "maneuver",
    "medevil": "medieval",
    ```: ```,
    "memento": "memento",
    "mention": "mention",
    "millenium": "millennium",
    "minature": "miniature",
    "miniscule": "minuscule",
    "mischevous": "mischievous",
    "mispell": "misspell",
    ```: ```,
    "monkies": "monkeys",
    "moral": "moral",
    "morgage": "mortgage",
    ```: ```,
    "murderer": "murderer",
    "mutiple": "multiple",
    "mystery": "mystery",
    "narative": "narrative",
    "neccessary": "necessary",
    "neice": "niece",
    ```: ```,
    "nieghbor": "neighbor",
    "ninty": "ninety",
    "noble": "noble",
    "noone": "no one",
    "noticable": "noticeable",
    "nowdays": "nowadays",
    "nucleus": "nucleus",
    ```: ```,
    ```: ```,
    ```: ```,
    ```: ```,
    ```: ```,
    "occasionaly": "occasionally",
    "occurrance": "occurrence",
    "occurence": "occurrence",
    ```: ```,
    ```: ```,
    "offically": "officially",
    "omited": "omitted",
    "oponent": "opponent",
    "oportunity": "opportunity",
    "oppurtunity": "opportunity",
    "optimisim": "optimism",
    "orchestra": "orchestra",
    "orientate": "orientate",
    ```: ```,
    ```: ```,
    ```: ```,
    "outragous": "outrageous",
    "overide": "override",
    "pacfic": "pacific",
    "pamplet": "pamphlet",
    "panick": "panic",
    ```: ```,
    ```: ```,
    "paralel": "parallel",
    ```: ```,
    "particually": "particularly",
    "pasttime": "pastime",
    ```: ```,
    ```: ```,
    ```: ```,
    ```: ```,
    "persistant": "persistent",
    ```: ```,
    "pharoah": "pharaoh",
    "phonetic": "phonetic",
    "physician": "physician",
    "plagarism": "plagiarism",
    "planing": "planning",
    "playwrite": "playwright",
    "pleasent": "pleasant",
    "ploting": "plotting",
    ```: ```,
    "polotics": "politics",
    ```: ```,
    "posession": "possession",
    ```: ```,
    "potatos": "potatoes",
    "practicle": "practical",
    ```: ```,
    "preceed": "precede",
    ```: ```,
    "preperation": "preparation",
    "presance": "presence",
    ```: ```,
    "priviledge": "privilege",
    "probly": "probably",
    "procede": "proceed",
    ```: ```,
    "pronounciation": "pronunciation",
    "prophesy": "prophesy",
    "proove": "prove",
    "publically": "publicly",
    ```: ```,
    "quarentine": "quarantine",
    "questionaire": "questionnaire",
    ```: ```,
    ```: ```,
    ```: ```,
    ```: ```,
    "reccomend": "recommend",
    "reccommend": "recommend",
    ```: ```,
    "recomend": "recommend",
    ```: ```,
    ```: ```,
    "relevent": "relevant",
    "religous": "religious",
    ```: ```,
    "rember": "remember",
    "repitition": "repetition",
    ```: ```,
    ```: ```,
    "restraunt": "restaurant",
    "releif": "relief",
    "religous": "religious",
    ```: ```,
    "resistence": "resistance",
    ```: ```,
    ```: ```,
    ```: ```,
    "rythm": "rhythm",
    ```: ```,
    "sacrafice": "sacrifice",
    "sadely": "sadly",
    "saftey": "safety",
    ```: ```,
    "sandwhich": "sandwich",
    ```: ```,
    "sargent": "sergeant",
    ```: ```,
    ```: ```,
    ```: ```,
    "scisors": "scissors",
    ```: ```,
    "secretery": "secretary",
    ```: ```,
    ```: ```,
    "seize": "seize",
    ```: ```,
    "sense": "sense",
    ```: ```,
    ```: ```,
    ```: ```,
    "sentance": "sentence",
    ```: ```,
    ```: ```,
    ```: ```,
    "sieze": "seize",
    ```: ```,
    ```: ```,
    ```: ```,
    "sincerly": "sincerely",
    ```: ```,
    "sissors": "scissors",
    ```: ```,
    "sixth": "sixth",
    "smoking": "smoking",
    "soild": "solid",
    "sofware": "software",
    ```: ```,
    ```: ```,
    ```: ```,
    ```: ```,
    ```: ```,
    "speach": "speech",
    ```: ```,
    ```: ```,
    "stomache": "stomach",
    ```: ```,
    ```: ```,
    ```: ```,
    "stragedy": "strategy",
    ```: ```,
    ```: ```,
    "strenght": "strength",
    ```: ```,
    ```: ```,
    "stuborn": "stubborn",
    ```: ```,
    "stupidly": "stupidly",
    ```: ```,
    ```: ```,
    "subpena": "subpoena",
    "succesful": "successful",
    ```: ```,
    ```: ```,
    ```: ```,
    ```: ```,
    ```: ```,
    "supercede": "supersede",
    ```: ```,
    ```: ```,
    "supposably": "supposedly",
    ```: ```,
    ```: ```,
    "suprise": "surprise",
    "surprize": "surprise",
    "suspence": "suspense",
    ```: ```,
    ```: ```,
    "symathy": "sympathy",
    ```: ```,
    ```: ```,
    "taste": "taste",
    ```: ```,
    ```: ```,
    "technolgy": "technology",
    ```: ```,
    ```: ```,
    ```: ```,
    "temperture": "temperature",
    ```: ```,
    "tendance": "tendency",
    ```: ```,
    "testemony": "testimony",
    ```: ```,
    ```: ```,
    ```: ```,
    ```: ```,
    "therefor": "therefore",
    ```: ```,
    "thouroughly": "thoroughly",
    ```: ```,
    ```: ```,
    ```: ```,
    ```: ```,
    ```: ```,
    "tommorow": "tomorrow",
    "tommorrow": "tomorrow",
    "tomorow": "tomorrow",
    ```: ```,
    "tonite": "tonight",
    ```: ```,
    ```: ```,
    ```: ```,
    ```: ```,
    ```: ```,
    ```: ```,
    "truley": "truly",
    "truely": "truly",
    "trustworthly": "trustworthy",
    ```: ```,
    ```: ```,
    ```: ```,
    "tyrany": "tyranny",
    ```: ```,
    ```: ```,
    ```: ```,
    "ultimatly": "ultimately",
    "umong": "among",
    "unanimous": "unanimous",
    "unattractive": "unattractive",
    ```: ```,
    "underate": "underrate",
    ```: ```,
    ```: ```,
    ```: ```,
    ```: ```,
    "unfortunatly": "unfortunately",
    ```: ```,
    "unfortuntely": "unfortunately",
    ```: ```,
    ```: ```,
    ```: ```,
    ```: ```,
    "unnecesary": "unnecessary",
    "unneccesary": "unnecessary",
    ```: ```,
    "unusal": "unusual",
    ```: ```,
    ```: ```,
    "upholstry": "upholstery",
    ```: ```,
    ```: ```,
    ```: ```,
    "usally": "usually",
    ```: ```,
    ```: ```,
    ```: ```,
    ```: ```,
    ```: ```,
    "vaccum": "vacuum",
    ```: ```,
    "valuble": "valuable",
    ```: ```,
    ```: ```,
    "vegatable": "vegetable",
    "vegitable": "vegetable",
    ```: ```,
    ```: ```,
    ```: ```,
    ```: ```,
    ```: ```,
    "villian": "villain",
    ```: ```,
    "visious": "vicious",
    ```: ```,
    ```: ```,
    ```: ```,
    "volenteer": "volunteer",
    ```: ```,
    ```: ```,
    ```: ```,
    ```: ```,
    "warrent": "warrant",
    ```: ```,
    ```: ```,
    ```: ```,
    "weigth": "weight",
    ```: ```,
    "whereever": "wherever",
    "whitch": "which",
    "wierd": "weird",
    "writting": "writing",
    ```: ```,
    ```: ```,
    ```: ```,
    ```: ```,
    "yatch": "yacht",
    ```: ```,
    "yearly": "yearly",
    ```: ```,
    "yonn": "yawn",
    "zeal": "zeal",
}

print(f"WARNING: Script has template literal placeholders. Fixing...")
