// ============================================================
// NEW LANGUAGE DICTIONARIES - IT, ZH-CN, ZH-TW, KO, JA, ID, TR
// ============================================================

const IT: Record<string, string> = {
  "Dashboard": "Cruscotto", "Tabela": "Tabella Prezzi", "Empréstimos": "Prestiti",
  "Trocas": "Scambi", "Doadores": "Donatori", "Leilões": "Aste",
  "Sorteios": "Estrazioni", "Lotérica": "Loteria", "Investidores": "Investitori",
  "Config Trocas": "Config. Scambi", "Compras & Vendas": "Acquisti e Vendite",
  "Estoque & Caixa": "Magazzino e Cassa", "Chat": "Chat",
  "Carregando...": "Caricamento...", "Carregando dados do banco...": "Caricamento dati banca...",
  "Carregando chat...": "Caricamento chat...", "Cancelar": "Annulla",
  "Entrar": "Entra", "Salvar": "Salva", "Fechar": "Chiudi",
  "Criar": "Crea", "Remover": "Rimuovi", "Registrar": "Registra",
  "Buscar...": "Cerca...", "Buscar item...": "Cerca oggetto...",
  "Buscar numero ou comprador...": "Cerca numero o acquirente...",
  "Nome": "Nome", "Item": "Oggetto", "Quantidade": "Quantità",
  "Tipo": "Tipo", "Data": "Data", "Player": "Giocatore",
  "Todos": "Tutti", "Admin": "Admin", "Modo visual": "Modalità visuale",
  "total": "totale", "registros": "registri",
  "Observação": "Nota", "Opcional": "Opzionale",
  "Dono": "Proprietario", "Moeda": "Valuta", "Ganhador": "Vincitore",
  "Vencedor": "Vincitore", "Participantes": "Partecipanti",
  "Criado": "Creato", "Qtd": "Qtà", "Inicial": "Iniziale",
  "Maior": "Più alto", "Lances": "Offerte", "Taxa": "Commissione",
  "Lucro": "Profitto", "Bruto:": "Lordo:", "Descrição": "Descrizione",
  "Origem": "Origine", "Ação": "Azione", "Disponível": "Disponibile",
  "Disponivel": "Disponibile",
  "Empréstimos Pendentes": "Prestiti in sospeso", "Empréstimos Pagos": "Prestiti pagati",
  "Investidores Ativos": "Investitori attivi", "Trocas Realizadas": "Scambi effettuati",
  "Registros no Caixa": "Registri in cassa", "Leilões Ativos": "Aste attive",
  "Sorteios Ativos": "Estrazioni attive", "Top 10 Doadores": "Top 10 Donatori",
  "Top 10 Investidores": "Top 10 Investitori", "Top 10 Contribuintes": "Top 10 Contributori",
  "Estoque do Banco": "Magazzino della Banca", "Movimentos do Caixa": "Movimenti di Cassa",
  "Eventos Ativos": "Eventi attivi",
  "Nenhum doador cadastrado.": "Nessun donatore registrato.",
  "Nenhum investidor cadastrado.": "Nessun investitore registrato.",
  "Nenhum contribuinte ainda. Contribua reportando precos na aba Tabela!": "Nessun contributore ancora. Contribuisci segnalando i prezzi nella scheda Tabella!",
  "Nenhum item encontrado.": "Nessun oggetto trovato.",
  "Estoque vazio.": "Magazzino vuoto.", "Nenhum registro ainda.": "Nessun registro ancora.",
  "desde": "dal", "contribuicoes": "contributi",
  "Posto de Trocas": "Posto di Scambio",
  "Sistema de gestao para sobreviventes": "Sistema di gestione per sopravvissuti",
  "Canais": "Canali", "Salas Privadas": "Stanze Private",
  "Geral": "Generale", "Atendimento": "Supporto", "Guias": "Guide",
  "Clãs": "Clan", "Comércio": "Commercio",
  "Nenhuma mensagem ainda. Seja o primeiro a conversar!": "Nessun messaggio ancora. Sii il primo!",
  "Nenhuma sala criada.": "Nessuna stanza creata.",
  "Nome da sala": "Nome della stanza", "Senha (opcional)": "Password (opzionale)",
  "Senha da sala": "Password della stanza", "Sala Privada": "Stanza Privata",
  "requer senha": "richiede password", "Voltar": "Indietro",
  "Hoje": "Oggi", "Ontem": "Ieri", "Membro": "Membro",
  "Regras:": "Regole:", "por": "di",
  "Digite seu nome para entrar no chat.": "Inserisci il tuo nome per entrare in chat.",
  "Seu nome no jogo": "Il tuo nome nel gioco",
  "Nenhuma mensagem ainda.": "Nessun messaggio ancora.",
  "Sala": "Stanza", "Mensagem": "Messaggio",
  "Evento": "Evento", "Sobreviventes": "Sopravvissuti",
  "Deletar sala": "Elimina stanza", "Deletar mensagem?": "Eliminare messaggio?",
  "❤️ Doadores": "❤️ Donatori",
  "Ranking": "Classifica", "Reordenar": "Riordina",
  "Nova Doação": "Nuova Donazione", "Registrar Doação": "Registra Donazione",
  "Histórico": "Cronologia", "Nenhuma doação.": "Nessuna donazione.",
  "Doação registrada!": "Donazione registrata!",
  "Excluir a doação de": "Elimina donazione di",
  "Excluir doação de": "Elimina donazione di",
  "💎 Membros Investidores": "💎 Membri Investitori",
  "Benefício:": "Vantaggio:",
  "em empréstimos e trocas": "su prestiti e scambi",
  "comum": "comune",
  "Como obter a tag?": "Come ottenere il tag?",
  "Ajude o banco — doando itens, fazendo trocas ou de qualquer outra forma.": "Aiuta la banca — donando oggetti, facendo scambi o in altro modo.",
  "Adicionar Investidor": "Aggiungi Investitore", "Nome do investidor": "Nome dell'investitore",
  "Adicionar": "Aggiungi", "Ativos": "Attivi",
  "Nenhum investidor.": "Nessun investitore.",
  "Valor Investido": "Valore Investito", "Data Entrada": "Data Ingresso",
  "Novo Investidor": "Nuovo Investitore", "Editar Investidor": "Modifica Investitore",
  "Status": "Stato", "Ativo": "Attivo", "Inativo": "Inattivo",
  "Investidor cadastrado!": "Investitore registrato!",
  "Investidor adicionado!": "Investitore aggiunto!",
  "Registro de Trocas": "Registro Scambi", "Nova Troca": "Nuovo Scambio",
  "Selecione": "Seleziona", "Nenhuma tabela": "Nessuna tabella",
  "Preencha o formulário ao lado.": "Compila il modulo accanto.",
  "sem taxa": "senza commissione", "Player Receibe:": "Giocatore Riceve:",
  "Player entregou:": "Giocatore ha consegnato:",
  "Sai do estoque do Banco:": "Esce dal magazzino della Banca:",
  "Entra no estoque do Banco:": "Entra nel magazzino della Banca:",
  "Entregou": "Consegnato", "Recebeu / Entrou no estoque": "Ricevuto / Entrato in magazzino",
  "Recibido / Entrou no estoque": "Ricevuto / Entrato in magazzino",
  "Calculadora": "Calcolatrice",
  "Troca registrada!": "Scambio registrato!",
  "Excluir troca e estornar estoque": "Elimina scambio e ripristina magazzino",
  "Troca excluída e estoque estornado.": "Scambio eliminato e magazzino ripristinato.",
  "Não foi possível excluir a troca.": "Impossibile eliminare lo scambio.",
  "Excluir a troca de": "Elimina lo scambio di",
  "Excluir a troca": "Elimina lo scambio",
  "Registrar Troca": "Registra Scambio",
  "Especial (0%)": "Speciale (0%)", "Top 10 (5%)": "Top 10 (5%)",
  "Investidor (10%)": "Investitore (10%)", "Comum (15%)": "Comune (15%)",
  "Não Contribuinte (20%)": "Non Contributore (20%)",
  "Banco (100% — troca interna)": "Banca (100% — scambio interno)",
  "Banco (100%)": "Banca (100%)", "Banco (100%):": "Banca (100%):",
  "⭐ Especial (0%)": "⭐ Speciale (0%)",
  "👑 Top 10 Investidor (5%)": "👑 Top 10 Investitore (5%)",
  "💎 Investidor (10%)": "💎 Investitore (10%)",
  "👤 Comum (15%)": "👤 Comune (15%)",
  "⚠️ Não Contribuinte (20%)": "⚠️ Non Contributore (20%)",
  "🛒 Compras e Vendas": "🛒 Acquisti e Vendite",
  "COMPRA:": "ACQUISTO:", "Você paga → Recebe do player": "Tu paghi → Ricevi dal giocatore",
  "VENDA:": "VENDITA:", "Você entrega → Recebe do player": "Tu consegni → Ricevi dal giocatore",
  "Entra": "Entra", "Sai": "Esce", "Paga": "Paga", "Recebe": "Riceve",
  "Compras": "Acquisti", "Vendas": "Vendite",
  "Nenhuma compra ou venda.": "Nessun acquisto o vendita.",
  "Registrar Compra": "Registra Acquisto", "Registrar Venda": "Registra Vendita",
  "Compra registrada!": "Acquisto registrato!", "Venda registrada!": "Vendita registrata!",
  "💰 Caixa do Banco": "💰 Cassa della Banca",
  "Saída por Leilão do Banco (100%)": "Uscita per Asta della Banca (100%)",
  "Registro Manual": "Registrazione Manuale",
  "ENTRADA": "ENTRATA", "SAÍDA": "USCITA",
  "Entrada": "Entrata", "Saída": "Uscita",
  "Nome do jogador": "Nome del giocatore",
  "Registrar Saída": "Registra Uscita", "Registrar Prêmio": "Registra Premio",
  "Estoque Atual": "Magazzino Attuale", "BAIXO": "BASSO",
  "Resetar": "Resetta", "Resetar TUDO?": "Resettare TUTTO?",
  "📦 ENTRADA": "📦 ENTRATA", "📤 SAÍDA": "📤 USCITA",
  "Nenhum registro.": "Nessun registro.",
  "🔨 Leilões": "🔨 Aste", "Como Funciona": "Come Funziona",
  "Novo Leilão": "Nuova Asta", "Criar Leilão": "Crea Asta",
  "Duração": "Durata", "Fila de Espera": "Coda d'attesa",
  "EM ESPERA": "IN ATTESA", "Nenhum leilão ativo.": "Nessun'asta attiva.",
  "Dar Lance": "Fai Offerta", "Finalizar Entrega": "Finalizza Consegna",
  "Histórico de Ganhadores": "Cronologia Vincitori",
  "Leilão criado!": "Asta creata!",
  "Lance deve ser > ": "L'offerta deve essere > ",
  "Lance de ": "Offerta di ", " registrado!": " registrata!",
  "Novo Sorteio": "Nuova Estrazione", "Nenhum.": "Nessuno.",
  "Participar": "Partecipa", "Sortear": "Estrai",
  "Encerrado": "Chiuso", "ENCERRADO": "CHIUSO",
  "Sorteio criado!": "Estrazione creata!", "Participando!": "Partecipazione!",
  "Historico de Ganhadores": "Cronologia Estrazioni",
  "Data do Sorteio": "Data Estrazione", "Todos os Participantes": "Tutti i Partecipanti",
  "Nenhum": "Nessuno", "Participar do Sorteio": "Partecipa all'Estrazione",
  "Participação registrada!": "Partecipazione registrata!",
  "Sorteio finalizado!": "Estrazione finalizzata!",
  "Lotérica Ativa": "Loteria Attiva", "Vendas abiertas": "Vendite aperte",
  "Sorteio realizado": "Estrazione effettuata", "Finalizada": "Finalizzata",
  "Configurando": "Configurazione", "Vendidos": "Venduti",
  "Arrecadado Total": "Totale Raccoldo",
  "Premio": "Premio", "Teve Ganhador!": "Abbiamo un Vincitore!",
  "Ninguem acertou - Premio acumulou!": "Nessuno ha indovinato - Premio accumulato!",
  "Finalizar Lotérica": "Finalizza Lotteria",
  "Vender Numero": "Vendi Numero", "Nome do Comprador": "Nome dell'Acquirente",
  "Vender": "Vendi", "Realizar Sorteio": "Esegui Estrazione",
  "Loterica criada!": "Loteria creata!",
  "Nova Lotérica": "Nuova Lotteria", "Configurar Lotérica": "Configura Lotteria",
  "Criar Lotérica": "Crea Lotteria",
  "Nenhuma lotérica ativa. Crie uma nova acima.": "Nessuna lotteria attiva. Creane una nuova sopra.",
  "Nenhuma lotérica ativa no momento.": "Nessuna lotteria attiva al momento.",
  "Regras do Banco": "Regole della Banca",
  "Membro Especial": "Membro Speciale", "Membro Comum": "Membro Comune",
  "Não Contribuinte": "Non Contributore",
  "Calculadora de Empréstimo": "Calcolatore Prestito",
  "Dias de Atraso": "Giorni di Ritardo", "Total a Devolver": "Totale da Restituire",
  "itens": "oggetti", "Novo Empréstimo": "Nuovo Prestito",
  "Pendentes": "In sospeso", "Pagos": "Pagati",
  "Nenhum empréstimo pendente.": "Nessun prestito in sospeso.",
  "Pendente": "In sospeso", "Pago": "Pagato", "Atrasado": "In ritardo",
  "Pagar": "Paga", "Confirmar Pagamento": "Conferma Pagamento",
  "Empréstimo registrado!": "Prestito registrato!",
  "Pagamento registrado!": "Pagamento registrato!",
  "Empréstimo excluído!": "Prestito eliminato!",
  "Excluir empréstimo?": "Eliminare il prestito?",
  "Tabela de Precos": "Tabella Prezzi", "Tabela de Preços": "Tabella Prezzi",
  "Reportar Precos": "Segnala Prezzi", "Reportar Preços": "Segnala Prezzi",
  "Alta": "Alta", "Media": "Media", "Baixa": "Bassa",
  "Comum": "Comune", "Incomum": "Non comune", "Raro": "Raro",
  "Lendario": "Leggendario", "Demanda": "Domanda", "Raridade": "Rarità",
  "Gerenciar Itens": "Gestisci Oggetti", "Reportar": "Segnala",
  "Editar": "Modifica", "Restaurar": "Ripristina",
  "Nome do Item *": "Nome Oggetto *", "Categoria *": "Categoria *",
  "Selecionar...": "Seleziona...", "Wiki Link": "Link Wiki",
  "Adicionar Item": "Aggiungi Oggetto",
  "Login Admin": "Login Admin", "Verificando...": "Verifica...",
  "Backup": "Backup", "Gerando...": "Generazione...",
  "Senha incorreta!": "Password errata!",
  "Modo Admin ativado!": "Modalità Admin attivata!",
  "Continuar em Português": "Continua in Portoghese",
  "Traduzir o Site": "Traduci il Sito", "Selecione seu idioma": "Seleziona la lingua",
  "Traduzir para": "Traduci in", "Traduzir site": "Traduci sito",
  "Registro adicionado!": "Registro aggiunto!",
  "Ordem atualizada!": "Ordine aggiornato!",
  "Preencha os obrigatórios.": "Compila i campi obbligatori.",
  "Preencha todos os campos.": "Compila tutti i campi.",
  "Preencha nome e valor.": "Compila nome e valore.",
  "Preencha o item e a quantidade.": "Compila oggetto e quantità.",
  "Preencha todos.": "Compila tutto.", "Remover?": "Rimuovere?",
  "Erro ao verificar senha.": "Errore nella verifica della password.",
  "Sem spam": "Niente spam",
  "Respeite todos os participantes": "Rispetta tutti i partecipanti",
  "Sem spam ou flood": "Niente spam o flood",
  "Configuração de Tabelas de Troca": "Configurazione Tabelle di Scambio",
  "Nova Regra": "Nuova Regola",
  "Nenhuma regra configurada.": "Nessuna regola configurata.",
  "Como funciona:": "Come funziona:",
  "Configuração salva!": "Configurazione salvata!",
};
